[package]
name = "pdf-graphics-skia"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-document = { path = "../pdf-document" }
pdf-canvas = { path = "../pdf-canvas" }
pdf-graphics = { path = "../pdf-graphics" }
skia-safe = { version = "0.89.0" }
thiserror = "2.0.12"