use std::{borrow::Cow, convert::TryFrom};

use pdf_object::{
    dictionary::Dictionary, object_resolver::ObjectResolver, object_variant::ObjectVariant,
};

use crate::error::FontError;

/// Represents the base encoding of a font.
#[derive(Default, PartialEq, Clone, Debug)]
pub enum FontEncoding {
    #[default]
    None,
    /// Standard encoding.
    Standard,
    /// Standard Mac Roman encoding.
    MacRoman,
    /// Mac Expert encoding.
    MacExpert,
    /// Windows ANSI encoding.
    WinAnsi,
    /// Unknown encoding.
    Unknown(String),
}

impl From<&str> for FontEncoding {
    fn from(name: &str) -> Self {
        match name {
            "MacRomanEncoding" => Self::MacRoman,
            "MacExpertEncoding" => Self::MacExpert,
            "StandardEncoding" => Self::Standard,
            "WinAnsiEncoding" => Self::WinAnsi,
            _ => Self::Unknown(name.to_owned()),
        }
    }
}

impl FontEncoding {
    /// Encodes UTF-8 text using the font encoding.
    pub fn encode(&self, text: &str) -> Result<Vec<u8>, FontError> {
        text.chars()
            .map(|character| self.encode_char(character))
            .collect()
    }

    /// Encodes a single Unicode scalar value using the font encoding.
    pub fn encode_char(&self, character: char) -> Result<u8, FontError> {
        match self {
            Self::WinAnsi => encode_win_ansi_char(character),
            _ => Err(FontError::UnsupportedTextEncoding(self.clone())),
        }
    }

    /// Decodes bytes using the font encoding.
    pub fn decode(&self, bytes: &[u8]) -> Result<String, FontError> {
        bytes
            .iter()
            .copied()
            .map(|byte| self.decode_byte(byte))
            .collect()
    }

    /// Decodes a single encoded byte using the font encoding.
    pub fn decode_byte(&self, byte: u8) -> Result<char, FontError> {
        match self {
            Self::WinAnsi => decode_win_ansi_byte(byte),
            _ => Err(FontError::UnsupportedTextEncoding(self.clone())),
        }
    }
}

#[derive(Debug)]
pub struct Encoding {
    pub names: Vec<Cow<'static, str>>,
}

impl Default for Encoding {
    fn default() -> Self {
        let names = names_from_base(&STANDARD_NAMES);
        Self { names }
    }
}

impl Encoding {
    /// Returns the built-in WinAnsi glyph-name table.
    pub fn win_ansi() -> Self {
        Self {
            names: names_from_base(&WIN_ANSI_NAMES),
        }
    }

    pub(crate) fn from_base_encoding(encoding: FontEncoding) -> Result<Self, FontError> {
        let names = match encoding {
            FontEncoding::Standard => names_from_base(&STANDARD_NAMES),
            FontEncoding::WinAnsi => names_from_base(&WIN_ANSI_NAMES),
            FontEncoding::MacRoman => names_from_base(&MAC_ROMAN_NAMES),
            FontEncoding::MacExpert => names_from_base(&MAC_EXPERT_NAMES),
            FontEncoding::Unknown(name) => {
                return Err(FontError::UnsupportedBaseEncoding(name));
            }
            FontEncoding::None => Vec::new(),
        };
        Ok(Self { names })
    }

    fn apply_differences(
        &mut self,
        differences_obj: &ObjectVariant,
        objects: &dyn ObjectResolver,
    ) -> Result<(), FontError> {
        let mut current_range_start = 0_usize;

        for chunk in differences_obj.try_array(objects)? {
            match chunk {
                ObjectVariant::Integer(_) => {
                    current_range_start = chunk.try_number::<usize>(objects)?;
                }
                _ => {
                    if let Some(slot) = self.names.get_mut(current_range_start) {
                        *slot = Cow::Owned(chunk.try_str(objects)?.to_owned());
                    }
                    current_range_start = current_range_start.saturating_add(1);
                }
            }
        }

        Ok(())
    }
}

impl Encoding {
    /// Parse the optional `/Encoding` entry from a font dictionary.
    pub fn from_dictionary(
        dictionary: &Dictionary,
        objects: &dyn ObjectResolver,
    ) -> Result<Option<Self>, FontError> {
        dictionary
            .get("Encoding")
            .map(|value| match objects.resolve_object(value)? {
                ObjectVariant::Dictionary(encoding_dictionary) => {
                    Self::from_encoding_dictionary(encoding_dictionary, objects)
                }
                other => Self::from_base_encoding(FontEncoding::from(other.try_str(objects)?)),
            })
            .transpose()
    }

    fn from_encoding_dictionary(
        dictionary: &Dictionary,
        objects: &dyn ObjectResolver,
    ) -> Result<Self, FontError> {
        let mut encoding = match dictionary.get("BaseEncoding") {
            Some(base) => {
                let base_encoding = FontEncoding::from(base.try_str(objects)?);
                Encoding::from_base_encoding(base_encoding)?
            }
            None => Self::default(),
        };

        if let Some(differences) = dictionary.get("Differences") {
            encoding.apply_differences(differences, objects)?;
        }

        Ok(encoding)
    }
}

fn names_from_base(base: &[&'static str]) -> Vec<Cow<'static, str>> {
    base.iter().map(|&nm| Cow::Borrowed(nm)).collect()
}

fn encode_win_ansi_char(character: char) -> Result<u8, FontError> {
    let code = u32::from(character);
    if code <= 0x7f || (0xa0..=0xff).contains(&code) {
        return u8::try_from(code)
            .map_err(|_| FontError::UnsupportedWinAnsiCharacter { character });
    }

    let byte = match character {
        '\u{20ac}' => 0x80,
        '\u{201a}' => 0x82,
        '\u{0192}' => 0x83,
        '\u{201e}' => 0x84,
        '\u{2026}' => 0x85,
        '\u{2020}' => 0x86,
        '\u{2021}' => 0x87,
        '\u{02c6}' => 0x88,
        '\u{2030}' => 0x89,
        '\u{0160}' => 0x8a,
        '\u{2039}' => 0x8b,
        '\u{0152}' => 0x8c,
        '\u{017d}' => 0x8e,
        '\u{2018}' => 0x91,
        '\u{2019}' => 0x92,
        '\u{201c}' => 0x93,
        '\u{201d}' => 0x94,
        '\u{2022}' => 0x95,
        '\u{2013}' => 0x96,
        '\u{2014}' => 0x97,
        '\u{02dc}' => 0x98,
        '\u{2122}' => 0x99,
        '\u{0161}' => 0x9a,
        '\u{203a}' => 0x9b,
        '\u{0153}' => 0x9c,
        '\u{017e}' => 0x9e,
        '\u{0178}' => 0x9f,
        _ => return Err(FontError::UnsupportedWinAnsiCharacter { character }),
    };
    Ok(byte)
}

fn decode_win_ansi_byte(byte: u8) -> Result<char, FontError> {
    let character = match byte {
        0x80 => '\u{20ac}',
        0x82 => '\u{201a}',
        0x83 => '\u{0192}',
        0x84 => '\u{201e}',
        0x85 => '\u{2026}',
        0x86 => '\u{2020}',
        0x87 => '\u{2021}',
        0x88 => '\u{02c6}',
        0x89 => '\u{2030}',
        0x8a => '\u{0160}',
        0x8b => '\u{2039}',
        0x8c => '\u{0152}',
        0x8e => '\u{017d}',
        0x91 => '\u{2018}',
        0x92 => '\u{2019}',
        0x93 => '\u{201c}',
        0x94 => '\u{201d}',
        0x95 => '\u{2022}',
        0x96 => '\u{2013}',
        0x97 => '\u{2014}',
        0x98 => '\u{02dc}',
        0x99 => '\u{2122}',
        0x9a => '\u{0161}',
        0x9b => '\u{203a}',
        0x9c => '\u{0153}',
        0x9e => '\u{017e}',
        0x9f => '\u{0178}',
        0x81 | 0x8d | 0x8f | 0x90 | 0x9d => {
            return Err(FontError::InvalidWinAnsiByte { byte });
        }
        _ => char::from_u32(u32::from(byte)).ok_or(FontError::InvalidWinAnsiByte { byte })?,
    };
    Ok(character)
}

const STANDARD_NAMES: [&str; 256] = [
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quoteright",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "quoteleft",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "exclamdown",
    "cent",
    "sterling",
    "fraction",
    "yen",
    "florin",
    "section",
    "currency",
    "quotesingle",
    "quotedblleft",
    "guillemotleft",
    "guilsinglleft",
    "guilsinglright",
    "fi",
    "fl",
    ".notdef",
    "endash",
    "dagger",
    "daggerdbl",
    "periodcentered",
    ".notdef",
    "paragraph",
    "bullet",
    "quotesinglbase",
    "quotedblbase",
    "quotedblright",
    "guillemotright",
    "ellipsis",
    "perthousand",
    ".notdef",
    "questiondown",
    ".notdef",
    "grave",
    "acute",
    "circumflex",
    "tilde",
    "macron",
    "breve",
    "dotaccent",
    "dieresis",
    ".notdef",
    "ring",
    "cedilla",
    ".notdef",
    "hungarumlaut",
    "ogonek",
    "caron",
    "emdash",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "AE",
    ".notdef",
    "ordfeminine",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "Lslash",
    "Oslash",
    "OE",
    "ordmasculine",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "ae",
    ".notdef",
    ".notdef",
    ".notdef",
    "dotlessi",
    ".notdef",
    ".notdef",
    "lslash",
    "oslash",
    "oe",
    "germandbls",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
];

const WIN_ANSI_NAMES: [&str; 256] = [
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quotesingle",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "grave",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    "bullet",
    "Euro",
    "bullet",
    "quotesinglbase",
    "florin",
    "quotedblbase",
    "ellipsis",
    "dagger",
    "daggerdbl",
    "circumflex",
    "perthousand",
    "Scaron",
    "guilsinglleft",
    "OE",
    "bullet",
    "Zcaron",
    "bullet",
    "bullet",
    "quoteleft",
    "quoteright",
    "quotedblleft",
    "quotedblright",
    "bullet",
    "endash",
    "emdash",
    "tilde",
    "trademark",
    "scaron",
    "guilsinglright",
    "oe",
    "bullet",
    "zcaron",
    "Ydieresis",
    "space",
    "exclamdown",
    "cent",
    "sterling",
    "currency",
    "yen",
    "brokenbar",
    "section",
    "dieresis",
    "copyright",
    "ordfeminine",
    "guillemotleft",
    "logicalnot",
    "hyphen",
    "registered",
    "macron",
    "degree",
    "plusminus",
    "twosuperior",
    "threesuperior",
    "acute",
    "mu",
    "paragraph",
    "periodcentered",
    "cedilla",
    "onesuperior",
    "ordmasculine",
    "guillemotright",
    "onequarter",
    "onehalf",
    "threequarters",
    "questiondown",
    "Agrave",
    "Aacute",
    "Acircumflex",
    "Atilde",
    "Adieresis",
    "Aring",
    "AE",
    "Ccedilla",
    "Egrave",
    "Eacute",
    "Ecircumflex",
    "Edieresis",
    "Igrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Eth",
    "Ntilde",
    "Ograve",
    "Oacute",
    "Ocircumflex",
    "Otilde",
    "Odieresis",
    "multiply",
    "Oslash",
    "Ugrave",
    "Uacute",
    "Ucircumflex",
    "Udieresis",
    "Yacute",
    "Thorn",
    "germandbls",
    "agrave",
    "aacute",
    "acircumflex",
    "atilde",
    "adieresis",
    "aring",
    "ae",
    "ccedilla",
    "egrave",
    "eacute",
    "ecircumflex",
    "edieresis",
    "igrave",
    "iacute",
    "icircumflex",
    "idieresis",
    "eth",
    "ntilde",
    "ograve",
    "oacute",
    "ocircumflex",
    "otilde",
    "odieresis",
    "divide",
    "oslash",
    "ugrave",
    "uacute",
    "ucircumflex",
    "udieresis",
    "yacute",
    "thorn",
    "ydieresis",
];

const MAC_ROMAN_NAMES: [&str; 256] = [
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "space",
    "exclam",
    "quotedbl",
    "numbersign",
    "dollar",
    "percent",
    "ampersand",
    "quotesingle",
    "parenleft",
    "parenright",
    "asterisk",
    "plus",
    "comma",
    "hyphen",
    "period",
    "slash",
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "colon",
    "semicolon",
    "less",
    "equal",
    "greater",
    "question",
    "at",
    "A",
    "B",
    "C",
    "D",
    "E",
    "F",
    "G",
    "H",
    "I",
    "J",
    "K",
    "L",
    "M",
    "N",
    "O",
    "P",
    "Q",
    "R",
    "S",
    "T",
    "U",
    "V",
    "W",
    "X",
    "Y",
    "Z",
    "bracketleft",
    "backslash",
    "bracketright",
    "asciicircum",
    "underscore",
    "grave",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "braceleft",
    "bar",
    "braceright",
    "asciitilde",
    ".notdef",
    "Adieresis",
    "Aring",
    "Ccedilla",
    "Eacute",
    "Ntilde",
    "Odieresis",
    "Udieresis",
    "aacute",
    "agrave",
    "acircumflex",
    "adieresis",
    "atilde",
    "aring",
    "ccedilla",
    "eacute",
    "egrave",
    "ecircumflex",
    "edieresis",
    "iacute",
    "igrave",
    "icircumflex",
    "idieresis",
    "ntilde",
    "oacute",
    "ograve",
    "ocircumflex",
    "odieresis",
    "otilde",
    "uacute",
    "ugrave",
    "ucircumflex",
    "udieresis",
    "dagger",
    "degree",
    "cent",
    "sterling",
    "section",
    "bullet",
    "paragraph",
    "germandbls",
    "registered",
    "copyright",
    "trademark",
    "acute",
    "dieresis",
    ".notdef",
    "AE",
    "Oslash",
    ".notdef",
    "plusminus",
    ".notdef",
    ".notdef",
    "yen",
    "mu",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "ordfeminine",
    "ordmasculine",
    ".notdef",
    "ae",
    "oslash",
    "questiondown",
    "exclamdown",
    "logicalnot",
    ".notdef",
    "florin",
    ".notdef",
    ".notdef",
    "guillemotleft",
    "guillemotright",
    "ellipsis",
    "space",
    "Agrave",
    "Atilde",
    "Otilde",
    "OE",
    "oe",
    "endash",
    "emdash",
    "quotedblleft",
    "quotedblright",
    "quoteleft",
    "quoteright",
    "divide",
    ".notdef",
    "ydieresis",
    "Ydieresis",
    "fraction",
    "currency",
    "guilsinglleft",
    "guilsinglright",
    "fi",
    "fl",
    "daggerdbl",
    "periodcentered",
    "quotesinglbase",
    "quotedblbase",
    "perthousand",
    "Acircumflex",
    "Ecircumflex",
    "Aacute",
    "Edieresis",
    "Egrave",
    "Iacute",
    "Icircumflex",
    "Idieresis",
    "Igrave",
    "Oacute",
    "Ocircumflex",
    ".notdef",
    "Ograve",
    "Uacute",
    "Ucircumflex",
    "Ugrave",
    "dotlessi",
    "circumflex",
    "tilde",
    "macron",
    "breve",
    "dotaccent",
    "ring",
    "cedilla",
    "hungarumlaut",
    "ogonek",
    "caron",
];

const MAC_EXPERT_NAMES: [&str; 256] = [
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "space",
    "exclamsmall",
    "Hungarumlautsmall",
    "centoldstyle",
    "dollaroldstyle",
    "dollarsuperior",
    "ampersandsmall",
    "Acutesmall",
    "parenleftsuperior",
    "parenrightsuperior",
    "twodotenleader",
    "onedotenleader",
    "comma",
    "hyphen",
    "period",
    "fraction",
    "zerooldstyle",
    "oneoldstyle",
    "twooldstyle",
    "threeoldstyle",
    "fouroldstyle",
    "fiveoldstyle",
    "sixoldstyle",
    "sevenoldstyle",
    "eightoldstyle",
    "nineoldstyle",
    "colon",
    "semicolon",
    ".notdef",
    "threequartersemdash",
    ".notdef",
    "questionsmall",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "Ethsmall",
    ".notdef",
    ".notdef",
    "onequarter",
    "onehalf",
    "threequarters",
    "oneeighth",
    "threeeighths",
    "fiveeighths",
    "seveneighths",
    "onethird",
    "twothirds",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "ff",
    "fi",
    "fl",
    "ffi",
    "ffl",
    "parenleftinferior",
    ".notdef",
    "parenrightinferior",
    "Circumflexsmall",
    "hypheninferior",
    "Gravesmall",
    "Asmall",
    "Bsmall",
    "Csmall",
    "Dsmall",
    "Esmall",
    "Fsmall",
    "Gsmall",
    "Hsmall",
    "Ismall",
    "Jsmall",
    "Ksmall",
    "Lsmall",
    "Msmall",
    "Nsmall",
    "Osmall",
    "Psmall",
    "Qsmall",
    "Rsmall",
    "Ssmall",
    "Tsmall",
    "Usmall",
    "Vsmall",
    "Wsmall",
    "Xsmall",
    "Ysmall",
    "Zsmall",
    "colonmonetary",
    "onefitted",
    "rupiah",
    "Tildesmall",
    ".notdef",
    ".notdef",
    "asuperior",
    "centsuperior",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "Aacutesmall",
    "Agravesmall",
    "Acircumflexsmall",
    "Adieresissmall",
    "Atildesmall",
    "Aringsmall",
    "Ccedillasmall",
    "Eacutesmall",
    "Egravesmall",
    "Ecircumflexsmall",
    "Edieresissmall",
    "Iacutesmall",
    "Igravesmall",
    "Icircumflexsmall",
    "Idieresissmall",
    "Ntildesmall",
    "Oacutesmall",
    "Ogravesmall",
    "Ocircumflexsmall",
    "Odieresissmall",
    "Otildesmall",
    "Uacutesmall",
    "Ugravesmall",
    "Ucircumflexsmall",
    "Udieresissmall",
    ".notdef",
    "eightsuperior",
    "fourinferior",
    "threeinferior",
    "sixinferior",
    "eightinferior",
    "seveninferior",
    "Scaronsmall",
    ".notdef",
    "centinferior",
    "twoinferior",
    ".notdef",
    "Dieresissmall",
    ".notdef",
    "Caronsmall",
    "osuperior",
    "fiveinferior",
    ".notdef",
    "commainferior",
    "periodinferior",
    "Yacutesmall",
    ".notdef",
    "dollarinferior",
    ".notdef",
    ".notdef",
    "Thornsmall",
    ".notdef",
    "nineinferior",
    "zeroinferior",
    "Zcaronsmall",
    "AEsmall",
    "Oslashsmall",
    "questiondownsmall",
    "oneinferior",
    "Lslashsmall",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "Cedillasmall",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "OEsmall",
    "figuredash",
    "hyphensuperior",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "exclamdownsmall",
    ".notdef",
    "Ydieresissmall",
    ".notdef",
    "onesuperior",
    "twosuperior",
    "threesuperior",
    "foursuperior",
    "fivesuperior",
    "sixsuperior",
    "sevensuperior",
    "ninesuperior",
    "zerosuperior",
    ".notdef",
    "esuperior",
    "rsuperior",
    "tsuperior",
    ".notdef",
    ".notdef",
    "isuperior",
    "ssuperior",
    "dsuperior",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
    "lsuperior",
    "Ogoneksmall",
    "Brevesmall",
    "Macronsmall",
    "bsuperior",
    "nsuperior",
    "msuperior",
    "commasuperior",
    "periodsuperior",
    "Dotaccentsmall",
    "Ringsmall",
    ".notdef",
    ".notdef",
    ".notdef",
    ".notdef",
];

#[cfg(test)]
mod tests {
    use super::{FontEncoding, FontError};

    #[test]
    fn win_ansi_round_trips_supported_text() {
        let text = "Euro \u{20ac}, caf\u{e9}, \u{201c}quoted\u{201d}";
        let encoded = FontEncoding::WinAnsi.encode(text).expect("encode");
        assert_eq!(
            FontEncoding::WinAnsi.decode(&encoded).expect("decode"),
            text
        );
    }

    #[test]
    fn win_ansi_encodes_special_characters() {
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{20ac}'), Ok(0x80));
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{201c}'), Ok(0x93));
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{201d}'), Ok(0x94));
    }

    #[test]
    fn win_ansi_rejects_unrepresentable_characters() {
        assert_eq!(
            FontEncoding::WinAnsi.encode_char('\u{1f642}'),
            Err(FontError::UnsupportedWinAnsiCharacter {
                character: '\u{1f642}'
            })
        );
    }

    #[test]
    fn win_ansi_rejects_undefined_bytes() {
        assert_eq!(
            FontEncoding::WinAnsi.decode_byte(0x81),
            Err(FontError::InvalidWinAnsiByte { byte: 0x81 })
        );
        assert_eq!(
            FontEncoding::WinAnsi.decode_byte(0x9d),
            Err(FontError::InvalidWinAnsiByte { byte: 0x9d })
        );
    }

    #[test]
    fn non_win_ansi_variants_are_rejected() {
        assert_eq!(
            FontEncoding::Standard.encode("test"),
            Err(FontError::UnsupportedTextEncoding(FontEncoding::Standard))
        );
        assert_eq!(
            FontEncoding::None.decode(b"test"),
            Err(FontError::UnsupportedTextEncoding(FontEncoding::None))
        );
    }
}
