use std::{borrow::Cow, convert::TryFrom};

use pdf_object::{
    dictionary::Dictionary, object_resolver::ObjectResolver, object_variant::ObjectVariant,
};

use crate::error::FontError;

/// Represents the base encoding of a font.
#[derive(Default, PartialEq, Clone, Debug)]
pub enum FontEncoding {
    #[default]
    None,
    /// Standard encoding.
    Standard,
    /// Standard Mac Roman encoding.
    MacRoman,
    /// Mac Expert encoding.
    MacExpert,
    /// Windows ANSI encoding.
    WinAnsi,
    /// Unknown encoding.
    Unknown(Vec<u8>),
}

impl From<&[u8]> for FontEncoding {
    fn from(name: &[u8]) -> Self {
        match name {
            b"MacRomanEncoding" => Self::MacRoman,
            b"MacExpertEncoding" => Self::MacExpert,
            b"StandardEncoding" => Self::Standard,
            b"WinAnsiEncoding" => Self::WinAnsi,
            _ => Self::Unknown(Vec::from(name)),
        }
    }
}

impl FontEncoding {
    /// Encodes UTF-8 text using the font encoding.
    pub fn encode(&self, text: &str) -> Result<Vec<u8>, FontError> {
        text.chars()
            .map(|character| self.encode_char(character))
            .collect()
    }

    /// Encodes a single Unicode scalar value using the font encoding.
    pub fn encode_char(&self, character: char) -> Result<u8, FontError> {
        match self {
            Self::WinAnsi => encode_win_ansi_char(character),
            _ => Err(FontError::UnsupportedTextEncoding(self.clone())),
        }
    }

    /// Decodes bytes using the font encoding.
    pub fn decode(&self, bytes: &[u8]) -> Result<String, FontError> {
        bytes
            .iter()
            .copied()
            .map(|byte| self.decode_byte(byte))
            .collect()
    }

    /// Decodes a single encoded byte using the font encoding.
    pub fn decode_byte(&self, byte: u8) -> Result<char, FontError> {
        match self {
            Self::WinAnsi => decode_win_ansi_byte(byte),
            _ => Err(FontError::UnsupportedTextEncoding(self.clone())),
        }
    }
}

#[derive(Debug)]
pub struct Encoding {
    pub names: Vec<Cow<'static, [u8]>>,
}

impl Default for Encoding {
    fn default() -> Self {
        let names = names_from_base(&STANDARD_NAMES);
        Self { names }
    }
}

impl Encoding {
    /// Returns the built-in WinAnsi glyph-name table.
    pub fn win_ansi() -> Self {
        Self {
            names: names_from_base(&WIN_ANSI_NAMES),
        }
    }

    pub(crate) fn from_base_encoding(encoding: FontEncoding) -> Result<Self, FontError> {
        let names = match encoding {
            FontEncoding::Standard => names_from_base(&STANDARD_NAMES),
            FontEncoding::WinAnsi => names_from_base(&WIN_ANSI_NAMES),
            FontEncoding::MacRoman => names_from_base(&MAC_ROMAN_NAMES),
            FontEncoding::MacExpert => names_from_base(&MAC_EXPERT_NAMES),
            FontEncoding::Unknown(name) => {
                return Err(FontError::UnsupportedBaseEncoding(
                    String::from_utf8_lossy(&name).into_owned(),
                ));
            }
            FontEncoding::None => Vec::new(),
        };
        Ok(Self { names })
    }

    fn apply_differences(
        &mut self,
        differences_obj: &ObjectVariant,
        objects: &dyn ObjectResolver,
    ) -> Result<(), FontError> {
        let mut current_range_start = 0_usize;

        for chunk in differences_obj.try_array(objects)? {
            match chunk {
                ObjectVariant::Integer(_) => {
                    current_range_start = chunk.try_number::<usize>(objects)?;
                }
                _ => {
                    if let Some(slot) = self.names.get_mut(current_range_start) {
                        *slot = Cow::Owned(Vec::from(chunk.try_name(objects)?));
                    }
                    current_range_start = current_range_start.saturating_add(1);
                }
            }
        }

        Ok(())
    }
}

impl Encoding {
    /// Parse the optional `/Encoding` entry from a font dictionary.
    pub fn from_dictionary(
        dictionary: &Dictionary,
        objects: &dyn ObjectResolver,
    ) -> Result<Option<Self>, FontError> {
        dictionary
            .get(b"Encoding")
            .map(|value| match objects.resolve_object(value)? {
                ObjectVariant::Dictionary(encoding_dictionary) => {
                    Self::from_encoding_dictionary(encoding_dictionary, objects)
                }
                other => Self::from_base_encoding(FontEncoding::from(other.try_name(objects)?)),
            })
            .transpose()
    }

    fn from_encoding_dictionary(
        dictionary: &Dictionary,
        objects: &dyn ObjectResolver,
    ) -> Result<Self, FontError> {
        let mut encoding = match dictionary.get(b"BaseEncoding") {
            Some(base) => {
                let base_encoding = FontEncoding::from(base.try_name(objects)?);
                Encoding::from_base_encoding(base_encoding)?
            }
            None => Self::default(),
        };

        if let Some(differences) = dictionary.get(b"Differences") {
            encoding.apply_differences(differences, objects)?;
        }

        Ok(encoding)
    }
}

fn names_from_base(base: &[&'static [u8]]) -> Vec<Cow<'static, [u8]>> {
    base.iter().map(|&nm| Cow::Borrowed(nm)).collect()
}

fn encode_win_ansi_char(character: char) -> Result<u8, FontError> {
    let code = u32::from(character);
    if code <= 0x7f || (0xa0..=0xff).contains(&code) {
        return u8::try_from(code)
            .map_err(|_| FontError::UnsupportedWinAnsiCharacter { character });
    }

    let byte = match character {
        '\u{20ac}' => 0x80,
        '\u{201a}' => 0x82,
        '\u{0192}' => 0x83,
        '\u{201e}' => 0x84,
        '\u{2026}' => 0x85,
        '\u{2020}' => 0x86,
        '\u{2021}' => 0x87,
        '\u{02c6}' => 0x88,
        '\u{2030}' => 0x89,
        '\u{0160}' => 0x8a,
        '\u{2039}' => 0x8b,
        '\u{0152}' => 0x8c,
        '\u{017d}' => 0x8e,
        '\u{2018}' => 0x91,
        '\u{2019}' => 0x92,
        '\u{201c}' => 0x93,
        '\u{201d}' => 0x94,
        '\u{2022}' => 0x95,
        '\u{2013}' => 0x96,
        '\u{2014}' => 0x97,
        '\u{02dc}' => 0x98,
        '\u{2122}' => 0x99,
        '\u{0161}' => 0x9a,
        '\u{203a}' => 0x9b,
        '\u{0153}' => 0x9c,
        '\u{017e}' => 0x9e,
        '\u{0178}' => 0x9f,
        _ => return Err(FontError::UnsupportedWinAnsiCharacter { character }),
    };
    Ok(byte)
}

fn decode_win_ansi_byte(byte: u8) -> Result<char, FontError> {
    let character = match byte {
        0x80 => '\u{20ac}',
        0x82 => '\u{201a}',
        0x83 => '\u{0192}',
        0x84 => '\u{201e}',
        0x85 => '\u{2026}',
        0x86 => '\u{2020}',
        0x87 => '\u{2021}',
        0x88 => '\u{02c6}',
        0x89 => '\u{2030}',
        0x8a => '\u{0160}',
        0x8b => '\u{2039}',
        0x8c => '\u{0152}',
        0x8e => '\u{017d}',
        0x91 => '\u{2018}',
        0x92 => '\u{2019}',
        0x93 => '\u{201c}',
        0x94 => '\u{201d}',
        0x95 => '\u{2022}',
        0x96 => '\u{2013}',
        0x97 => '\u{2014}',
        0x98 => '\u{02dc}',
        0x99 => '\u{2122}',
        0x9a => '\u{0161}',
        0x9b => '\u{203a}',
        0x9c => '\u{0153}',
        0x9e => '\u{017e}',
        0x9f => '\u{0178}',
        0x81 | 0x8d | 0x8f | 0x90 | 0x9d => {
            return Err(FontError::InvalidWinAnsiByte { byte });
        }
        _ => char::from_u32(u32::from(byte)).ok_or(FontError::InvalidWinAnsiByte { byte })?,
    };
    Ok(character)
}

const STANDARD_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quoteright",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"quoteleft",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"exclamdown",
    b"cent",
    b"sterling",
    b"fraction",
    b"yen",
    b"florin",
    b"section",
    b"currency",
    b"quotesingle",
    b"quotedblleft",
    b"guillemotleft",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b".notdef",
    b"endash",
    b"dagger",
    b"daggerdbl",
    b"periodcentered",
    b".notdef",
    b"paragraph",
    b"bullet",
    b"quotesinglbase",
    b"quotedblbase",
    b"quotedblright",
    b"guillemotright",
    b"ellipsis",
    b"perthousand",
    b".notdef",
    b"questiondown",
    b".notdef",
    b"grave",
    b"acute",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"dieresis",
    b".notdef",
    b"ring",
    b"cedilla",
    b".notdef",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
    b"emdash",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"AE",
    b".notdef",
    b"ordfeminine",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Lslash",
    b"Oslash",
    b"OE",
    b"ordmasculine",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ae",
    b".notdef",
    b".notdef",
    b".notdef",
    b"dotlessi",
    b".notdef",
    b".notdef",
    b"lslash",
    b"oslash",
    b"oe",
    b"germandbls",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
];

const WIN_ANSI_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b"bullet",
    b"Euro",
    b"bullet",
    b"quotesinglbase",
    b"florin",
    b"quotedblbase",
    b"ellipsis",
    b"dagger",
    b"daggerdbl",
    b"circumflex",
    b"perthousand",
    b"Scaron",
    b"guilsinglleft",
    b"OE",
    b"bullet",
    b"Zcaron",
    b"bullet",
    b"bullet",
    b"quoteleft",
    b"quoteright",
    b"quotedblleft",
    b"quotedblright",
    b"bullet",
    b"endash",
    b"emdash",
    b"tilde",
    b"trademark",
    b"scaron",
    b"guilsinglright",
    b"oe",
    b"bullet",
    b"zcaron",
    b"Ydieresis",
    b"space",
    b"exclamdown",
    b"cent",
    b"sterling",
    b"currency",
    b"yen",
    b"brokenbar",
    b"section",
    b"dieresis",
    b"copyright",
    b"ordfeminine",
    b"guillemotleft",
    b"logicalnot",
    b"hyphen",
    b"registered",
    b"macron",
    b"degree",
    b"plusminus",
    b"twosuperior",
    b"threesuperior",
    b"acute",
    b"mu",
    b"paragraph",
    b"periodcentered",
    b"cedilla",
    b"onesuperior",
    b"ordmasculine",
    b"guillemotright",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"questiondown",
    b"Agrave",
    b"Aacute",
    b"Acircumflex",
    b"Atilde",
    b"Adieresis",
    b"Aring",
    b"AE",
    b"Ccedilla",
    b"Egrave",
    b"Eacute",
    b"Ecircumflex",
    b"Edieresis",
    b"Igrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Eth",
    b"Ntilde",
    b"Ograve",
    b"Oacute",
    b"Ocircumflex",
    b"Otilde",
    b"Odieresis",
    b"multiply",
    b"Oslash",
    b"Ugrave",
    b"Uacute",
    b"Ucircumflex",
    b"Udieresis",
    b"Yacute",
    b"Thorn",
    b"germandbls",
    b"agrave",
    b"aacute",
    b"acircumflex",
    b"atilde",
    b"adieresis",
    b"aring",
    b"ae",
    b"ccedilla",
    b"egrave",
    b"eacute",
    b"ecircumflex",
    b"edieresis",
    b"igrave",
    b"iacute",
    b"icircumflex",
    b"idieresis",
    b"eth",
    b"ntilde",
    b"ograve",
    b"oacute",
    b"ocircumflex",
    b"otilde",
    b"odieresis",
    b"divide",
    b"oslash",
    b"ugrave",
    b"uacute",
    b"ucircumflex",
    b"udieresis",
    b"yacute",
    b"thorn",
    b"ydieresis",
];

const MAC_ROMAN_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b".notdef",
    b"Adieresis",
    b"Aring",
    b"Ccedilla",
    b"Eacute",
    b"Ntilde",
    b"Odieresis",
    b"Udieresis",
    b"aacute",
    b"agrave",
    b"acircumflex",
    b"adieresis",
    b"atilde",
    b"aring",
    b"ccedilla",
    b"eacute",
    b"egrave",
    b"ecircumflex",
    b"edieresis",
    b"iacute",
    b"igrave",
    b"icircumflex",
    b"idieresis",
    b"ntilde",
    b"oacute",
    b"ograve",
    b"ocircumflex",
    b"odieresis",
    b"otilde",
    b"uacute",
    b"ugrave",
    b"ucircumflex",
    b"udieresis",
    b"dagger",
    b"degree",
    b"cent",
    b"sterling",
    b"section",
    b"bullet",
    b"paragraph",
    b"germandbls",
    b"registered",
    b"copyright",
    b"trademark",
    b"acute",
    b"dieresis",
    b".notdef",
    b"AE",
    b"Oslash",
    b".notdef",
    b"plusminus",
    b".notdef",
    b".notdef",
    b"yen",
    b"mu",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ordfeminine",
    b"ordmasculine",
    b".notdef",
    b"ae",
    b"oslash",
    b"questiondown",
    b"exclamdown",
    b"logicalnot",
    b".notdef",
    b"florin",
    b".notdef",
    b".notdef",
    b"guillemotleft",
    b"guillemotright",
    b"ellipsis",
    b"space",
    b"Agrave",
    b"Atilde",
    b"Otilde",
    b"OE",
    b"oe",
    b"endash",
    b"emdash",
    b"quotedblleft",
    b"quotedblright",
    b"quoteleft",
    b"quoteright",
    b"divide",
    b".notdef",
    b"ydieresis",
    b"Ydieresis",
    b"fraction",
    b"currency",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b"daggerdbl",
    b"periodcentered",
    b"quotesinglbase",
    b"quotedblbase",
    b"perthousand",
    b"Acircumflex",
    b"Ecircumflex",
    b"Aacute",
    b"Edieresis",
    b"Egrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Igrave",
    b"Oacute",
    b"Ocircumflex",
    b".notdef",
    b"Ograve",
    b"Uacute",
    b"Ucircumflex",
    b"Ugrave",
    b"dotlessi",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"ring",
    b"cedilla",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
];

const MAC_EXPERT_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclamsmall",
    b"Hungarumlautsmall",
    b"centoldstyle",
    b"dollaroldstyle",
    b"dollarsuperior",
    b"ampersandsmall",
    b"Acutesmall",
    b"parenleftsuperior",
    b"parenrightsuperior",
    b"twodotenleader",
    b"onedotenleader",
    b"comma",
    b"hyphen",
    b"period",
    b"fraction",
    b"zerooldstyle",
    b"oneoldstyle",
    b"twooldstyle",
    b"threeoldstyle",
    b"fouroldstyle",
    b"fiveoldstyle",
    b"sixoldstyle",
    b"sevenoldstyle",
    b"eightoldstyle",
    b"nineoldstyle",
    b"colon",
    b"semicolon",
    b".notdef",
    b"threequartersemdash",
    b".notdef",
    b"questionsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Ethsmall",
    b".notdef",
    b".notdef",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"oneeighth",
    b"threeeighths",
    b"fiveeighths",
    b"seveneighths",
    b"onethird",
    b"twothirds",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ff",
    b"fi",
    b"fl",
    b"ffi",
    b"ffl",
    b"parenleftinferior",
    b".notdef",
    b"parenrightinferior",
    b"Circumflexsmall",
    b"hypheninferior",
    b"Gravesmall",
    b"Asmall",
    b"Bsmall",
    b"Csmall",
    b"Dsmall",
    b"Esmall",
    b"Fsmall",
    b"Gsmall",
    b"Hsmall",
    b"Ismall",
    b"Jsmall",
    b"Ksmall",
    b"Lsmall",
    b"Msmall",
    b"Nsmall",
    b"Osmall",
    b"Psmall",
    b"Qsmall",
    b"Rsmall",
    b"Ssmall",
    b"Tsmall",
    b"Usmall",
    b"Vsmall",
    b"Wsmall",
    b"Xsmall",
    b"Ysmall",
    b"Zsmall",
    b"colonmonetary",
    b"onefitted",
    b"rupiah",
    b"Tildesmall",
    b".notdef",
    b".notdef",
    b"asuperior",
    b"centsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Aacutesmall",
    b"Agravesmall",
    b"Acircumflexsmall",
    b"Adieresissmall",
    b"Atildesmall",
    b"Aringsmall",
    b"Ccedillasmall",
    b"Eacutesmall",
    b"Egravesmall",
    b"Ecircumflexsmall",
    b"Edieresissmall",
    b"Iacutesmall",
    b"Igravesmall",
    b"Icircumflexsmall",
    b"Idieresissmall",
    b"Ntildesmall",
    b"Oacutesmall",
    b"Ogravesmall",
    b"Ocircumflexsmall",
    b"Odieresissmall",
    b"Otildesmall",
    b"Uacutesmall",
    b"Ugravesmall",
    b"Ucircumflexsmall",
    b"Udieresissmall",
    b".notdef",
    b"eightsuperior",
    b"fourinferior",
    b"threeinferior",
    b"sixinferior",
    b"eightinferior",
    b"seveninferior",
    b"Scaronsmall",
    b".notdef",
    b"centinferior",
    b"twoinferior",
    b".notdef",
    b"Dieresissmall",
    b".notdef",
    b"Caronsmall",
    b"osuperior",
    b"fiveinferior",
    b".notdef",
    b"commainferior",
    b"periodinferior",
    b"Yacutesmall",
    b".notdef",
    b"dollarinferior",
    b".notdef",
    b".notdef",
    b"Thornsmall",
    b".notdef",
    b"nineinferior",
    b"zeroinferior",
    b"Zcaronsmall",
    b"AEsmall",
    b"Oslashsmall",
    b"questiondownsmall",
    b"oneinferior",
    b"Lslashsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Cedillasmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"OEsmall",
    b"figuredash",
    b"hyphensuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"exclamdownsmall",
    b".notdef",
    b"Ydieresissmall",
    b".notdef",
    b"onesuperior",
    b"twosuperior",
    b"threesuperior",
    b"foursuperior",
    b"fivesuperior",
    b"sixsuperior",
    b"sevensuperior",
    b"ninesuperior",
    b"zerosuperior",
    b".notdef",
    b"esuperior",
    b"rsuperior",
    b"tsuperior",
    b".notdef",
    b".notdef",
    b"isuperior",
    b"ssuperior",
    b"dsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"lsuperior",
    b"Ogoneksmall",
    b"Brevesmall",
    b"Macronsmall",
    b"bsuperior",
    b"nsuperior",
    b"msuperior",
    b"commasuperior",
    b"periodsuperior",
    b"Dotaccentsmall",
    b"Ringsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
];

#[cfg(test)]
mod tests {
    use super::{FontEncoding, FontError};

    #[test]
    fn win_ansi_round_trips_supported_text() {
        let text = "Euro \u{20ac}, caf\u{e9}, \u{201c}quoted\u{201d}";
        let encoded = FontEncoding::WinAnsi.encode(text).expect("encode");
        assert_eq!(
            FontEncoding::WinAnsi.decode(&encoded).expect("decode"),
            text
        );
    }

    #[test]
    fn win_ansi_encodes_special_characters() {
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{20ac}'), Ok(0x80));
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{201c}'), Ok(0x93));
        assert_eq!(FontEncoding::WinAnsi.encode_char('\u{201d}'), Ok(0x94));
    }

    #[test]
    fn win_ansi_rejects_unrepresentable_characters() {
        assert_eq!(
            FontEncoding::WinAnsi.encode_char('\u{1f642}'),
            Err(FontError::UnsupportedWinAnsiCharacter {
                character: '\u{1f642}'
            })
        );
    }

    #[test]
    fn win_ansi_rejects_undefined_bytes() {
        assert_eq!(
            FontEncoding::WinAnsi.decode_byte(0x81),
            Err(FontError::InvalidWinAnsiByte { byte: 0x81 })
        );
        assert_eq!(
            FontEncoding::WinAnsi.decode_byte(0x9d),
            Err(FontError::InvalidWinAnsiByte { byte: 0x9d })
        );
    }

    #[test]
    fn non_win_ansi_variants_are_rejected() {
        assert_eq!(
            FontEncoding::Standard.encode("test"),
            Err(FontError::UnsupportedTextEncoding(FontEncoding::Standard))
        );
        assert_eq!(
            FontEncoding::None.decode(b"test"),
            Err(FontError::UnsupportedTextEncoding(FontEncoding::None))
        );
    }
}
