//! Simple-font encoding tables, PDF differences, and WinAnsi text conversion.

use crate::{font::GlyphName, pdf::SimpleEncoding};
use std::{borrow::Cow, convert::TryFrom, sync::Arc};

use pdf_object_reader::{
    DictionaryContext, FromPdfObject, ObjectAccess, ObjectContext, ReadResult,
    object_variant::ObjectVariant,
};

use crate::{base_encoding::BaseEncoding, error::FontError};

/// Glyph names indexed by character code after applying encoding differences.
#[derive(Debug)]
pub struct Encoding {
    /// The base encoding table with any PDF Differences applied.
    pub names: Vec<Cow<'static, [u8]>>,
}

impl Default for Encoding {
    fn default() -> Self {
        let names = names_from_base(&STANDARD_NAMES);
        Self { names }
    }
}

impl Encoding {
    /// Returns the built-in WinAnsi glyph-name table.
    pub fn win_ansi() -> Self {
        Self {
            names: names_from_base(&WIN_ANSI_NAMES),
        }
    }

    /// Builds a base table, leaving built-in font encodings empty.
    pub(crate) fn from_base_encoding(encoding: BaseEncoding) -> Result<Self, FontError> {
        let names = match encoding {
            BaseEncoding::Standard => names_from_base(&STANDARD_NAMES),
            BaseEncoding::WinAnsi => names_from_base(&WIN_ANSI_NAMES),
            BaseEncoding::MacRoman => names_from_base(&MAC_ROMAN_NAMES),
            BaseEncoding::MacExpert => names_from_base(&MAC_EXPERT_NAMES),
            BaseEncoding::Unknown(name) => {
                return Err(FontError::UnsupportedBaseEncoding(
                    String::from_utf8_lossy(&name).into_owned(),
                ));
            }
            BaseEncoding::BuiltIn => Vec::new(),
        };
        Ok(Self { names })
    }

    /// Reads the optional `/Encoding` name or dictionary from a font dictionary.
    ///
    /// Missing or null entries return `None`. Invalid entries retain contextual
    /// reader errors; unsupported base names are reported as font error sources.
    pub fn from_dictionary(
        context: &mut DictionaryContext<'_, impl ObjectAccess + ?Sized>,
    ) -> ReadResult<Option<Self>> {
        context.optional(b"Encoding")
    }
}

impl TryFrom<BaseEncoding> for Encoding {
    type Error = FontError;

    /// Builds a glyph-name table, rejecting unsupported named encodings.
    fn try_from(encoding: BaseEncoding) -> Result<Self, Self::Error> {
        Self::from_base_encoding(encoding)
    }
}

impl FromPdfObject for Encoding {
    /// Reads a base-encoding name or an encoding dictionary in the active traversal.
    fn from_pdf_object(context: ObjectContext<'_, impl ObjectAccess + ?Sized>) -> ReadResult<Self> {
        if !matches!(context.object().value(), ObjectVariant::Dictionary(_)) {
            let name = Arc::<[u8]>::from_pdf_object(context)?;
            return Ok(Self::try_from(BaseEncoding::from(name.as_ref()))?);
        }
        let mut context = context.dictionary()?;
        let mut encoding = match context.optional::<Arc<[u8]>>(b"BaseEncoding")? {
            Some(name) => Self::try_from(BaseEncoding::from(name.as_ref()))?,
            None => Self::default(),
        };
        if let Some(differences) = context.optional::<EncodingDifferences>(b"Differences")? {
            for (code, name) in differences.0 {
                if let Some(slot) = encoding.names.get_mut(usize::from(code)) {
                    *slot = Cow::Owned(name);
                }
            }
        }
        Ok(encoding)
    }
}

/// Valid one-byte replacements, retaining the last name assigned to each code.
struct EncodingDifferences(std::collections::BTreeMap<u8, Vec<u8>>);

impl FromPdfObject for EncodingDifferences {
    fn from_pdf_object(context: ObjectContext<'_, impl ObjectAccess + ?Sized>) -> ReadResult<Self> {
        let mut context = context.array()?;
        let mut names = std::collections::BTreeMap::new();
        let mut code = 0_usize;
        for index in 0..context.array().len() {
            if matches!(context.array().get(index), Some(ObjectVariant::Integer(_))) {
                code = context.at(index)?;
            } else {
                // Ignore names outside the one-byte encoding table without reading them.
                if let Ok(code) = u8::try_from(code) {
                    let name: std::sync::Arc<[u8]> = context.at(index)?;
                    names.insert(code, name.to_vec());
                }
                code = code.saturating_add(1);
            }
        }
        Ok(Self(names))
    }
}

/// Normalizes a simple encoding, leaving symbolic fonts to use their built-in names.
pub(crate) fn simple_encoding(
    context: &mut DictionaryContext<'_, impl ObjectAccess + ?Sized>,
    symbolic: bool,
) -> ReadResult<SimpleEncoding> {
    let encoding = Encoding::from_dictionary(context)?.unwrap_or_else(|| {
        if symbolic {
            Encoding { names: Vec::new() }
        } else {
            Encoding::default()
        }
    });
    let differences = encoding
        .names
        .iter()
        .enumerate()
        .filter_map(|(index, name)| {
            u8::try_from(index)
                .ok()
                .map(|code| (code, GlyphName(Arc::from(name.as_ref()))))
        })
        .collect();
    Ok(SimpleEncoding {
        base: BaseEncoding::BuiltIn,
        differences,
    })
}

/// Borrows static glyph names until a PDF difference replaces them.
fn names_from_base(base: &[&'static [u8]]) -> Vec<Cow<'static, [u8]>> {
    base.iter().map(|&nm| Cow::Borrowed(nm)).collect()
}

/// Encodes a Unicode character as a WinAnsi byte, rejecting unsupported characters.
pub(crate) fn encode_win_ansi_char(character: char) -> Result<u8, FontError> {
    let code = u32::from(character);
    if code <= 0x7f || (0xa0..=0xff).contains(&code) {
        return u8::try_from(code)
            .map_err(|_| FontError::UnsupportedWinAnsiCharacter { character });
    }

    let byte = match character {
        '\u{20ac}' => 0x80,
        '\u{201a}' => 0x82,
        '\u{0192}' => 0x83,
        '\u{201e}' => 0x84,
        '\u{2026}' => 0x85,
        '\u{2020}' => 0x86,
        '\u{2021}' => 0x87,
        '\u{02c6}' => 0x88,
        '\u{2030}' => 0x89,
        '\u{0160}' => 0x8a,
        '\u{2039}' => 0x8b,
        '\u{0152}' => 0x8c,
        '\u{017d}' => 0x8e,
        '\u{2018}' => 0x91,
        '\u{2019}' => 0x92,
        '\u{201c}' => 0x93,
        '\u{201d}' => 0x94,
        '\u{2022}' => 0x95,
        '\u{2013}' => 0x96,
        '\u{2014}' => 0x97,
        '\u{02dc}' => 0x98,
        '\u{2122}' => 0x99,
        '\u{0161}' => 0x9a,
        '\u{203a}' => 0x9b,
        '\u{0153}' => 0x9c,
        '\u{017e}' => 0x9e,
        '\u{0178}' => 0x9f,
        _ => return Err(FontError::UnsupportedWinAnsiCharacter { character }),
    };
    Ok(byte)
}

/// Decodes a WinAnsi byte, rejecting undefined code points.
pub(crate) fn decode_win_ansi_byte(byte: u8) -> Result<char, FontError> {
    let character = match byte {
        0x80 => '\u{20ac}',
        0x82 => '\u{201a}',
        0x83 => '\u{0192}',
        0x84 => '\u{201e}',
        0x85 => '\u{2026}',
        0x86 => '\u{2020}',
        0x87 => '\u{2021}',
        0x88 => '\u{02c6}',
        0x89 => '\u{2030}',
        0x8a => '\u{0160}',
        0x8b => '\u{2039}',
        0x8c => '\u{0152}',
        0x8e => '\u{017d}',
        0x91 => '\u{2018}',
        0x92 => '\u{2019}',
        0x93 => '\u{201c}',
        0x94 => '\u{201d}',
        0x95 => '\u{2022}',
        0x96 => '\u{2013}',
        0x97 => '\u{2014}',
        0x98 => '\u{02dc}',
        0x99 => '\u{2122}',
        0x9a => '\u{0161}',
        0x9b => '\u{203a}',
        0x9c => '\u{0153}',
        0x9e => '\u{017e}',
        0x9f => '\u{0178}',
        0x81 | 0x8d | 0x8f | 0x90 | 0x9d => {
            return Err(FontError::InvalidWinAnsiByte { byte });
        }
        _ => char::from_u32(u32::from(byte)).ok_or(FontError::InvalidWinAnsiByte { byte })?,
    };
    Ok(character)
}

const STANDARD_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quoteright",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"quoteleft",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"exclamdown",
    b"cent",
    b"sterling",
    b"fraction",
    b"yen",
    b"florin",
    b"section",
    b"currency",
    b"quotesingle",
    b"quotedblleft",
    b"guillemotleft",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b".notdef",
    b"endash",
    b"dagger",
    b"daggerdbl",
    b"periodcentered",
    b".notdef",
    b"paragraph",
    b"bullet",
    b"quotesinglbase",
    b"quotedblbase",
    b"quotedblright",
    b"guillemotright",
    b"ellipsis",
    b"perthousand",
    b".notdef",
    b"questiondown",
    b".notdef",
    b"grave",
    b"acute",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"dieresis",
    b".notdef",
    b"ring",
    b"cedilla",
    b".notdef",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
    b"emdash",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"AE",
    b".notdef",
    b"ordfeminine",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Lslash",
    b"Oslash",
    b"OE",
    b"ordmasculine",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ae",
    b".notdef",
    b".notdef",
    b".notdef",
    b"dotlessi",
    b".notdef",
    b".notdef",
    b"lslash",
    b"oslash",
    b"oe",
    b"germandbls",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
];

const WIN_ANSI_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b"bullet",
    b"Euro",
    b"bullet",
    b"quotesinglbase",
    b"florin",
    b"quotedblbase",
    b"ellipsis",
    b"dagger",
    b"daggerdbl",
    b"circumflex",
    b"perthousand",
    b"Scaron",
    b"guilsinglleft",
    b"OE",
    b"bullet",
    b"Zcaron",
    b"bullet",
    b"bullet",
    b"quoteleft",
    b"quoteright",
    b"quotedblleft",
    b"quotedblright",
    b"bullet",
    b"endash",
    b"emdash",
    b"tilde",
    b"trademark",
    b"scaron",
    b"guilsinglright",
    b"oe",
    b"bullet",
    b"zcaron",
    b"Ydieresis",
    b"space",
    b"exclamdown",
    b"cent",
    b"sterling",
    b"currency",
    b"yen",
    b"brokenbar",
    b"section",
    b"dieresis",
    b"copyright",
    b"ordfeminine",
    b"guillemotleft",
    b"logicalnot",
    b"hyphen",
    b"registered",
    b"macron",
    b"degree",
    b"plusminus",
    b"twosuperior",
    b"threesuperior",
    b"acute",
    b"mu",
    b"paragraph",
    b"periodcentered",
    b"cedilla",
    b"onesuperior",
    b"ordmasculine",
    b"guillemotright",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"questiondown",
    b"Agrave",
    b"Aacute",
    b"Acircumflex",
    b"Atilde",
    b"Adieresis",
    b"Aring",
    b"AE",
    b"Ccedilla",
    b"Egrave",
    b"Eacute",
    b"Ecircumflex",
    b"Edieresis",
    b"Igrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Eth",
    b"Ntilde",
    b"Ograve",
    b"Oacute",
    b"Ocircumflex",
    b"Otilde",
    b"Odieresis",
    b"multiply",
    b"Oslash",
    b"Ugrave",
    b"Uacute",
    b"Ucircumflex",
    b"Udieresis",
    b"Yacute",
    b"Thorn",
    b"germandbls",
    b"agrave",
    b"aacute",
    b"acircumflex",
    b"atilde",
    b"adieresis",
    b"aring",
    b"ae",
    b"ccedilla",
    b"egrave",
    b"eacute",
    b"ecircumflex",
    b"edieresis",
    b"igrave",
    b"iacute",
    b"icircumflex",
    b"idieresis",
    b"eth",
    b"ntilde",
    b"ograve",
    b"oacute",
    b"ocircumflex",
    b"otilde",
    b"odieresis",
    b"divide",
    b"oslash",
    b"ugrave",
    b"uacute",
    b"ucircumflex",
    b"udieresis",
    b"yacute",
    b"thorn",
    b"ydieresis",
];

const MAC_ROMAN_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclam",
    b"quotedbl",
    b"numbersign",
    b"dollar",
    b"percent",
    b"ampersand",
    b"quotesingle",
    b"parenleft",
    b"parenright",
    b"asterisk",
    b"plus",
    b"comma",
    b"hyphen",
    b"period",
    b"slash",
    b"zero",
    b"one",
    b"two",
    b"three",
    b"four",
    b"five",
    b"six",
    b"seven",
    b"eight",
    b"nine",
    b"colon",
    b"semicolon",
    b"less",
    b"equal",
    b"greater",
    b"question",
    b"at",
    b"A",
    b"B",
    b"C",
    b"D",
    b"E",
    b"F",
    b"G",
    b"H",
    b"I",
    b"J",
    b"K",
    b"L",
    b"M",
    b"N",
    b"O",
    b"P",
    b"Q",
    b"R",
    b"S",
    b"T",
    b"U",
    b"V",
    b"W",
    b"X",
    b"Y",
    b"Z",
    b"bracketleft",
    b"backslash",
    b"bracketright",
    b"asciicircum",
    b"underscore",
    b"grave",
    b"a",
    b"b",
    b"c",
    b"d",
    b"e",
    b"f",
    b"g",
    b"h",
    b"i",
    b"j",
    b"k",
    b"l",
    b"m",
    b"n",
    b"o",
    b"p",
    b"q",
    b"r",
    b"s",
    b"t",
    b"u",
    b"v",
    b"w",
    b"x",
    b"y",
    b"z",
    b"braceleft",
    b"bar",
    b"braceright",
    b"asciitilde",
    b".notdef",
    b"Adieresis",
    b"Aring",
    b"Ccedilla",
    b"Eacute",
    b"Ntilde",
    b"Odieresis",
    b"Udieresis",
    b"aacute",
    b"agrave",
    b"acircumflex",
    b"adieresis",
    b"atilde",
    b"aring",
    b"ccedilla",
    b"eacute",
    b"egrave",
    b"ecircumflex",
    b"edieresis",
    b"iacute",
    b"igrave",
    b"icircumflex",
    b"idieresis",
    b"ntilde",
    b"oacute",
    b"ograve",
    b"ocircumflex",
    b"odieresis",
    b"otilde",
    b"uacute",
    b"ugrave",
    b"ucircumflex",
    b"udieresis",
    b"dagger",
    b"degree",
    b"cent",
    b"sterling",
    b"section",
    b"bullet",
    b"paragraph",
    b"germandbls",
    b"registered",
    b"copyright",
    b"trademark",
    b"acute",
    b"dieresis",
    b".notdef",
    b"AE",
    b"Oslash",
    b".notdef",
    b"plusminus",
    b".notdef",
    b".notdef",
    b"yen",
    b"mu",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ordfeminine",
    b"ordmasculine",
    b".notdef",
    b"ae",
    b"oslash",
    b"questiondown",
    b"exclamdown",
    b"logicalnot",
    b".notdef",
    b"florin",
    b".notdef",
    b".notdef",
    b"guillemotleft",
    b"guillemotright",
    b"ellipsis",
    b"space",
    b"Agrave",
    b"Atilde",
    b"Otilde",
    b"OE",
    b"oe",
    b"endash",
    b"emdash",
    b"quotedblleft",
    b"quotedblright",
    b"quoteleft",
    b"quoteright",
    b"divide",
    b".notdef",
    b"ydieresis",
    b"Ydieresis",
    b"fraction",
    b"currency",
    b"guilsinglleft",
    b"guilsinglright",
    b"fi",
    b"fl",
    b"daggerdbl",
    b"periodcentered",
    b"quotesinglbase",
    b"quotedblbase",
    b"perthousand",
    b"Acircumflex",
    b"Ecircumflex",
    b"Aacute",
    b"Edieresis",
    b"Egrave",
    b"Iacute",
    b"Icircumflex",
    b"Idieresis",
    b"Igrave",
    b"Oacute",
    b"Ocircumflex",
    b".notdef",
    b"Ograve",
    b"Uacute",
    b"Ucircumflex",
    b"Ugrave",
    b"dotlessi",
    b"circumflex",
    b"tilde",
    b"macron",
    b"breve",
    b"dotaccent",
    b"ring",
    b"cedilla",
    b"hungarumlaut",
    b"ogonek",
    b"caron",
];

const MAC_EXPERT_NAMES: [&[u8]; 256] = [
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"space",
    b"exclamsmall",
    b"Hungarumlautsmall",
    b"centoldstyle",
    b"dollaroldstyle",
    b"dollarsuperior",
    b"ampersandsmall",
    b"Acutesmall",
    b"parenleftsuperior",
    b"parenrightsuperior",
    b"twodotenleader",
    b"onedotenleader",
    b"comma",
    b"hyphen",
    b"period",
    b"fraction",
    b"zerooldstyle",
    b"oneoldstyle",
    b"twooldstyle",
    b"threeoldstyle",
    b"fouroldstyle",
    b"fiveoldstyle",
    b"sixoldstyle",
    b"sevenoldstyle",
    b"eightoldstyle",
    b"nineoldstyle",
    b"colon",
    b"semicolon",
    b".notdef",
    b"threequartersemdash",
    b".notdef",
    b"questionsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Ethsmall",
    b".notdef",
    b".notdef",
    b"onequarter",
    b"onehalf",
    b"threequarters",
    b"oneeighth",
    b"threeeighths",
    b"fiveeighths",
    b"seveneighths",
    b"onethird",
    b"twothirds",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"ff",
    b"fi",
    b"fl",
    b"ffi",
    b"ffl",
    b"parenleftinferior",
    b".notdef",
    b"parenrightinferior",
    b"Circumflexsmall",
    b"hypheninferior",
    b"Gravesmall",
    b"Asmall",
    b"Bsmall",
    b"Csmall",
    b"Dsmall",
    b"Esmall",
    b"Fsmall",
    b"Gsmall",
    b"Hsmall",
    b"Ismall",
    b"Jsmall",
    b"Ksmall",
    b"Lsmall",
    b"Msmall",
    b"Nsmall",
    b"Osmall",
    b"Psmall",
    b"Qsmall",
    b"Rsmall",
    b"Ssmall",
    b"Tsmall",
    b"Usmall",
    b"Vsmall",
    b"Wsmall",
    b"Xsmall",
    b"Ysmall",
    b"Zsmall",
    b"colonmonetary",
    b"onefitted",
    b"rupiah",
    b"Tildesmall",
    b".notdef",
    b".notdef",
    b"asuperior",
    b"centsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Aacutesmall",
    b"Agravesmall",
    b"Acircumflexsmall",
    b"Adieresissmall",
    b"Atildesmall",
    b"Aringsmall",
    b"Ccedillasmall",
    b"Eacutesmall",
    b"Egravesmall",
    b"Ecircumflexsmall",
    b"Edieresissmall",
    b"Iacutesmall",
    b"Igravesmall",
    b"Icircumflexsmall",
    b"Idieresissmall",
    b"Ntildesmall",
    b"Oacutesmall",
    b"Ogravesmall",
    b"Ocircumflexsmall",
    b"Odieresissmall",
    b"Otildesmall",
    b"Uacutesmall",
    b"Ugravesmall",
    b"Ucircumflexsmall",
    b"Udieresissmall",
    b".notdef",
    b"eightsuperior",
    b"fourinferior",
    b"threeinferior",
    b"sixinferior",
    b"eightinferior",
    b"seveninferior",
    b"Scaronsmall",
    b".notdef",
    b"centinferior",
    b"twoinferior",
    b".notdef",
    b"Dieresissmall",
    b".notdef",
    b"Caronsmall",
    b"osuperior",
    b"fiveinferior",
    b".notdef",
    b"commainferior",
    b"periodinferior",
    b"Yacutesmall",
    b".notdef",
    b"dollarinferior",
    b".notdef",
    b".notdef",
    b"Thornsmall",
    b".notdef",
    b"nineinferior",
    b"zeroinferior",
    b"Zcaronsmall",
    b"AEsmall",
    b"Oslashsmall",
    b"questiondownsmall",
    b"oneinferior",
    b"Lslashsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"Cedillasmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"OEsmall",
    b"figuredash",
    b"hyphensuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"exclamdownsmall",
    b".notdef",
    b"Ydieresissmall",
    b".notdef",
    b"onesuperior",
    b"twosuperior",
    b"threesuperior",
    b"foursuperior",
    b"fivesuperior",
    b"sixsuperior",
    b"sevensuperior",
    b"ninesuperior",
    b"zerosuperior",
    b".notdef",
    b"esuperior",
    b"rsuperior",
    b"tsuperior",
    b".notdef",
    b".notdef",
    b"isuperior",
    b"ssuperior",
    b"dsuperior",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
    b"lsuperior",
    b"Ogoneksmall",
    b"Brevesmall",
    b"Macronsmall",
    b"bsuperior",
    b"nsuperior",
    b"msuperior",
    b"commasuperior",
    b"periodsuperior",
    b"Dotaccentsmall",
    b"Ringsmall",
    b".notdef",
    b".notdef",
    b".notdef",
    b".notdef",
];

#[cfg(test)]
mod tests {
    use super::FontError;
    use crate::BaseEncoding;

    #[test]
    fn win_ansi_round_trips_supported_text() {
        let text = "Euro \u{20ac}, caf\u{e9}, \u{201c}quoted\u{201d}";
        let encoded = BaseEncoding::WinAnsi.encode(text).expect("encode");
        assert_eq!(
            BaseEncoding::WinAnsi.decode(&encoded).expect("decode"),
            text
        );
    }

    #[test]
    fn win_ansi_encodes_special_characters() {
        assert_eq!(BaseEncoding::WinAnsi.encode_char('\u{20ac}'), Ok(0x80));
        assert_eq!(BaseEncoding::WinAnsi.encode_char('\u{201c}'), Ok(0x93));
        assert_eq!(BaseEncoding::WinAnsi.encode_char('\u{201d}'), Ok(0x94));
    }

    #[test]
    fn win_ansi_rejects_unrepresentable_characters() {
        assert_eq!(
            BaseEncoding::WinAnsi.encode_char('\u{1f642}'),
            Err(FontError::UnsupportedWinAnsiCharacter {
                character: '\u{1f642}'
            })
        );
    }

    #[test]
    fn win_ansi_rejects_undefined_bytes() {
        assert_eq!(
            BaseEncoding::WinAnsi.decode_byte(0x81),
            Err(FontError::InvalidWinAnsiByte { byte: 0x81 })
        );
        assert_eq!(
            BaseEncoding::WinAnsi.decode_byte(0x9d),
            Err(FontError::InvalidWinAnsiByte { byte: 0x9d })
        );
    }

    #[test]
    fn non_win_ansi_variants_are_rejected() {
        assert_eq!(
            BaseEncoding::Standard.encode("test"),
            Err(FontError::UnsupportedTextEncoding(BaseEncoding::Standard))
        );
        assert_eq!(
            BaseEncoding::BuiltIn.decode(b"test"),
            Err(FontError::UnsupportedTextEncoding(BaseEncoding::BuiltIn))
        );
    }
}
