[package]
name = "pdf-graphics"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
