// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Horizontal alignment of annotation text.
 */
export type Alignment = "left" | "center" | "right";

/**
 * Owned AnnotationAction data retained from the source PDF.
 */
export type AnnotationAction = { "GoTo": {
/**
 * The destination.
 */
destination: AnnotationDestination, } } | { "GoToRemote": {
/**
 * The file specification.
 */
file_specification: FileSpecification,
/**
 * The destination.
 */
destination: AnnotationDestination | null,
/**
 * Whether to open in a new window.
 */
new_window: boolean | null, } } | { "Uri": {
/**
 * The URI bytes.
 */
uri: Array<number>,
/**
 * Whether to treat the URI as a map request.
 */
is_map: boolean | null, } } | { "Launch": {
/**
 * The file specification.
 */
file_specification: FileSpecification | null, } } | { "Named": {
/**
 * The action name.
 */
name: Array<number>, } } | { "SubmitForm": {
/**
 * The file specification.
 */
file_specification: FileSpecification | null,
/**
 * The field names.
 */
fields: Array<Array<number>> | null,
/**
 * The submit flags.
 */
flags: number | null, } } | { "ResetForm": {
/**
 * The field names.
 */
fields: Array<Array<number>> | null,
/**
 * The reset flags.
 */
flags: number | null, } } | { "ImportData": {
/**
 * The file specification.
 */
file_specification: FileSpecification, } } | { "JavaScript": {
/**
 * The script bytes.
 */
script: Array<number>, } } | { "SetOCGState": {
/**
 * The OCG state names.
 */
state: Array<Array<number>>,
/**
 * Whether to preserve the radiobutton state.
 */
preserve_rb: boolean | null, } } | { "Rendition": {
/**
 * The operation code.
 */
operation: number | null, } } | { "Trans": {
/**
 * The duration.
 */
duration: number | null, } } | "GoTo3DView" | { "Unknown": {
/**
 * The action subtype name.
 */
action_type: Array<number>, } };

/**
 * Owned AnnotationBorder data retained from the source PDF.
 */
export type AnnotationBorder = {
/**
 * Horizontal corner radius.
 */
horizontal_radius: number,
/**
 * Vertical corner radius.
 */
vertical_radius: number,
/**
 * Border width.
 */
width: number,
/**
 * Optional validated dash pattern; `None` is a solid border.
 */
dash_pattern: DashPattern | null, };

/**
 * Browser context for a Core command; omit `target` for programmatic operations.
 */
export type AnnotationCommandRequest = {
/**
 * Optional mounted control context to validate before dispatch.
 */
target: AnnotationTarget | null,
/**
 * Reject the edit if another accepted command has advanced this revision.
 */
expected_revision: Revision,
/**
 * Semantic edit already resolved from GUI input and coordinate transforms.
 */
operation: Operation, };

/**
 * Owned AnnotationDestination data retained from the source PDF.
 */
export type AnnotationDestination = { "Named": {
/**
 * Raw destination name bytes.
 */
name: Array<number>, } } | { "Explicit": ExplicitDestination };

/**
 * Engine-allocated identity, unique within a document and never reused there.
 */
export type AnnotationId = string;

/**
 * Core-owned annotation vocabulary; future variants can extend the boundary.
 */
export type AnnotationKind = { "kind": "highlight", "data": Highlight } | { "kind": "text_note", "data": TextNote } | { "kind": "ink", "data": Ink } | { "kind": "widget", "data": Widget } | { "kind": "free_text", "data": FreeText } | { "kind": "link", "data": Link } | { "kind": "line", "data": PathAnnotation } | { "kind": "square", "data": BoxAnnotation } | { "kind": "circle", "data": BoxAnnotation } | { "kind": "polygon", "data": PathAnnotation } | { "kind": "poly_line", "data": PathAnnotation } | { "kind": "underline", "data": Markup } | { "kind": "squiggly", "data": Markup } | { "kind": "strike_out", "data": Markup } | { "kind": "stamp", "data": Stamp } | { "kind": "caret", "data": Caret } | { "kind": "popup", "data": Popup } | { "kind": "unknown", "data": UnknownAnnotation };

/**
 * Common live capabilities plus an optional immutable source snapshot.
 */
export type AnnotationMetadata = {
/**
 * Live PDF annotation flag bits, including unknown bits; zero is unrestricted.
 */
flags: number,
/**
 * Source snapshot for inspection and future export. Its values are historical,
 * never a fallback that overrides current geometry, content, or field values.
 * Source references belong to the containing document's PDF.
 */
source: SourceAnnotation | null,
/**
 * Current host-owned action metadata; storing it never executes the action.
 */
action: AnnotationAction | null, };

/**
 * Acknowledgement of a committed in-memory edit, never a storage acknowledgement.
 */
export type AnnotationReceipt = {
/**
 * Core event containing the new document revision.
 */
event: Event,
/**
 * Pages whose annotation presentation must be refreshed.
 */
pages: Array<number>, };

/**
 * Captured mounted control context, separate from the document revision.
 */
export type AnnotationTarget = {
/**
 * Page owning the mounted control.
 */
page: number,
/**
 * Core identity rendered by the control.
 */
annotation_id: AnnotationId,
/**
 * Viewport revision captured when the draft or drag began.
 */
viewport_revision: number, };

/**
 * Owned AppearanceCharacteristics data retained from the source PDF.
 */
export type AppearanceCharacteristics = {
/**
 * The rotation in degrees.
 */
rotation: number | null,
/**
 * The border color.
 */
border_color: Color | null,
/**
 * The background color.
 */
background_color: Color | null,
/**
 * The normal caption.
 */
normal_caption: Array<number> | null,
/**
 * The rollover caption.
 */
rollover_caption: Array<number> | null,
/**
 * The alternate caption.
 */
alternate_caption: Array<number> | null, };

/**
 * Owned AppearanceDictionary data retained from the source PDF.
 */
export type AppearanceDictionary = {
/**
 * Normal-state names; no drawing resources are retained.
 */
normal_states: Array<Array<number>>, };

/**
 * Owned BorderEffect data retained from the source PDF.
 */
export type BorderEffect = {
/**
 * The effect style.
 */
style: BorderEffectStyle | null,
/**
 * The intensity.
 */
intensity: number | null, };

/**
 * Owned BorderEffectStyle data retained from the source PDF.
 */
export type BorderEffectStyle = "None" | "Cloudy" | { "Unknown": Array<number> };

/**
 * Owned BorderStyle data retained from the source PDF.
 */
export type BorderStyle = {
/**
 * Border width.
 */
width: number | null,
/**
 * Border style name.
 */
style: BorderStyleName | null,
/**
 * Optional dash pattern.
 */
dash_pattern: Array<number> | null, };

/**
 * Owned BorderStyleName data retained from the source PDF.
 */
export type BorderStyleName = "Solid" | "Dashed" | "Beveled" | "Inset" | "Underline" | { "Unknown": Array<number> };

/**
 * Rectangular or elliptical shape, with PDF decoration metadata retained.
 */
export type BoxAnnotation = {
/**
 * Page-space rectangle enclosing the shape.
 */
bounds: Rect,
/**
 * Current stroke/fill style.
 */
style: ResolvedStyle,
/**
 * Optional border effect, which may be unsupported by a host.
 */
border_effect: BorderEffect | null,
/**
 * Optional left, top, right, bottom difference rectangle.
 */
insets: [number, number, number, number] | null, };

/**
 * Push button that triggers a host-owned action and never holds a value.
 */
export type ButtonField = {
/**
 * Unicode caption shown on the button.
 */
caption: string, };

/**
 * Caret annotation retained without claiming native rendering support.
 */
export type Caret = {
/**
 * Placement rectangle.
 */
bounds: Rect,
/**
 * Legacy caret properties.
 */
properties: CaretAnnotation, };

/**
 * Owned CaretAnnotation data retained from the source PDF.
 */
export type CaretAnnotation = {
/**
 * The difference rectangle.
 */
difference_rect: [number, number, number, number] | null,
/**
 * The caret style.
 */
style: CaretSymbolStyle | null, };

/**
 * Owned CaretSymbolStyle data retained from the source PDF.
 */
export type CaretSymbolStyle = "P" | "None" | { "Unknown": Array<number> };

/**
 * Invalidation information for the GUI's annotation presentation.
 */
export type Change = { "change": "created", "data": AnnotationId } | { "change": "updated", "data": AnnotationId } | { "change": "deleted", "data": AnnotationId } | { "change": "field_created", "data": FieldId } | { "change": "field_deleted", "data": FieldId } | { "change": "field_updated", "data": {
/**
 * Shared field whose value command was accepted.
 */
field: FieldId,
/**
 * Every referencing widget ID, without duplicates, in annotation insertion order.
 * Includes all radio options and repeated views; empty for an unplaced field.
 */
widgets: Array<AnnotationId>, } };

/**
 * Shared boolean value displayed by every checkbox bound to the field.
 */
export type CheckboxField = {
/**
 * Whether the field is checked; required unchecked fields are incomplete.
 */
checked: boolean, };

/**
 * Checkbox views whose export states share one exclusive field value.
 */
export type CheckboxGroupField = {
/**
 * Nonempty options in document order; repeated views share an option identity.
 */
options: Array<ChoiceOption>,
/**
 * Selected export state, or an unchecked draft.
 */
selected: OptionId | null, };

/**
 * An option whose identity remains distinct even when export values coincide.
 */
export type ChoiceOption = {
/**
 * Caller-supplied identity, unique within this field's option collection.
 */
id: OptionId,
/**
 * User-facing option label.
 */
label: string,
/**
 * Value for a future form exporter; Core selection uses the identity.
 */
export_value: string, };

/**
 * Owned CircleAnnotation data retained from the source PDF.
 */
export type CircleAnnotation = {
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The interior color.
 */
interior_color: Color | null,
/**
 * The border effect.
 */
border_effect: BorderEffect | null,
/**
 * The difference rectangle.
 */
difference_rect: [number, number, number, number] | null, };

/**
 * Unpremultiplied color with RGBA channel
 */
export type Color = { r: number, g: number, b: number, a: number, };

/**
 * A dropdown with optional arbitrary text entry.
 */
export type ComboBoxField = {
/**
 * Options in presentation order, each with a unique identity; may be empty.
 */
options: Array<ChoiceOption>,
/**
 * Whether custom text values are accepted.
 */
editable: boolean,
/**
 * Current selection or custom text.
 */
value: ComboValue, };

/**
 * Combo value distinguishes no selection, a known option, and arbitrary text.
 */
export type ComboValue = { "kind": "empty" } | { "kind": "option", "value": OptionId } | { "kind": "text", "value": string };

/**
 * Field semantics the host maps back into Core commands.
 */
export type ControlKind = "text" | "checkbox" | "checkbox_group" | "radio" | "list_box" | "combo_box" | "button";

/**
 * Host element family presenting a widget's field value.
 */
export type ControlTag = "input" | "text_area" | "select" | "button";

/**
 * Dash pattern used for stroking paths.
 */
export type DashPattern = {
/**
 * Alternating dash and gap lengths.
 */
intervals: Array<number>,
/**
 * Distance into the dash pattern where stroking starts.
 */
phase: number, };

/**
 * Owned DestinationTarget data retained from the source PDF.
 */
export type DestinationTarget = "Dictionary" | { "Reference": {
/**
 * PDF object number, distinct from Core annotation and field identities.
 */
number: string,
/**
 * PDF generation number.
 */
generation: string, } };

/**
 * A committed edit result; failures produce an error instead of an event.
 */
export type Event = {
/**
 * Document revision after the edit, exactly one beyond its prior revision.
 */
revision: Revision,
/**
 * Identity and nature of the change; inspect the engine for current content.
 */
change: Change, };

/**
 * Owned ExplicitDestination data retained from the source PDF.
 */
export type ExplicitDestination = { "Xyz": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Left coordinate.
 */
left: number | null,
/**
 * Top coordinate.
 */
top: number | null,
/**
 * Zoom factor.
 */
zoom: number | null, } } | { "Fit": {
/**
 * The page target.
 */
page: DestinationTarget, } } | { "FitH": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Top coordinate.
 */
top: number | null, } } | { "FitV": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Left coordinate.
 */
left: number | null, } } | { "FitR": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Left coordinate.
 */
left: number,
/**
 * Bottom coordinate.
 */
bottom: number,
/**
 * Right coordinate.
 */
right: number,
/**
 * Top coordinate.
 */
top: number, } } | { "FitB": {
/**
 * The page target.
 */
page: DestinationTarget, } } | { "FitBH": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Top coordinate.
 */
top: number | null, } } | { "FitBV": {
/**
 * The page target.
 */
page: DestinationTarget,
/**
 * Left coordinate.
 */
left: number | null, } };

/**
 * Core-allocated document-local identity, distinct from an annotation identity.
 */
export type FieldId = string;

/**
 * Typed field configuration and value; field kinds cannot change through edits.
 */
export type FieldKind = { "kind": "text", "data": TextField } | { "kind": "checkbox", "data": CheckboxField } | { "kind": "checkbox_group", "data": CheckboxGroupField } | { "kind": "radio", "data": RadioField } | { "kind": "list_box", "data": ListBoxField } | { "kind": "combo_box", "data": ComboBoxField } | { "kind": "button", "data": ButtonField } | { "kind": "unsupported", "data": UnsupportedField };

/**
 * Historical PDF field state. Live normalized values remain in `FieldKind`.
 */
export type FieldMetadata = {
/**
 * Original terminal field/widget metadata, including defaults, raw names,
 * flags, options, values, actions, and additional-action dictionaries.
 * These values never overwrite subsequent Core value commands.
 */
source: WidgetAnnotation | null, };

/**
 * Owned FileSpecification data retained from the source PDF.
 */
export type FileSpecification = { "Dictionary": FileSpecificationDictionary } | { "Path": Array<number> };

/**
 * Owned FileSpecificationDictionary data retained from the source PDF.
 */
export type FileSpecificationDictionary = {
/**
 * The file system name.
 */
file_system: Array<number> | null,
/**
 * The platform-independent file name.
 */
file_name: Array<number> | null,
/**
 * The Unicode file name.
 */
unicode_file_name: Array<number> | null,
/**
 * The macOS file name.
 */
mac_file_name: Array<number> | null,
/**
 * The DOS file name.
 */
dos_file_name: Array<number> | null,
/**
 * The Unix file name.
 */
unix_file_name: Array<number> | null,
/**
 * Whether the file is volatile.
 */
volatile: boolean | null, };

/**
 * Styled page text, distinct from an anchored comment.
 */
export type FreeText = {
/**
 * Page-space placement.
 */
bounds: Rect,
/**
 * Current Unicode text.
 */
text: string,
/**
 * Current text and border style.
 */
style: FreeTextStyle,
/**
 * Rich text retained without claiming a rich-text editor or renderer.
 */
rich_contents: Array<number> | null,
/**
 * Optional open two- or three-point callout, translated with the annotation.
 */
callout: Polyline | null,
/**
 * Retained border effect, unsupported by the plain-text editor.
 */
border_effect: BorderEffect | null, };

/**
 * Owned FreeTextAnnotation data retained from the source PDF.
 */
export type FreeTextAnnotation = {
/**
 * The default appearance string.
 */
default_appearance: Array<number> | null,
/**
 * The quadding mode.
 */
quadding: number | null,
/**
 * Rich text contents.
 */
rich_contents: Array<number> | null,
/**
 * The default style string.
 */
default_style: Array<number> | null,
/**
 * The open callout line, from its starting point to its attachment point.
 */
callout_line: Polyline | null,
/**
 * The border effect.
 */
border_effect: BorderEffect | null,
/**
 * The difference rectangle.
 */
difference_rect: [number, number, number, number] | null,
/**
 * The intent.
 */
intent: Array<number> | null, };

/**
 * Solid free-text border in page units.
 */
export type FreeTextBorder = {
/**
 * Unquantized opaque sRGB color.
 */
color: Color,
/**
 * Nonnegative border width.
 */
width: number, };

/**
 * Explicit native free-text style, independent of retained PDF source metadata.
 */
export type FreeTextStyle = {
/**
 * Plain PDF font resource name; no slash or PDF delimiters.
 */
font_name: Array<number>,
/**
 * Strictly positive font size in page units.
 */
font_size: number,
/**
 * Unquantized opaque text sRGB color.
 */
text_color: Color,
/**
 * Optional solid border.
 */
border: FreeTextBorder | null,
/**
 * Nonnegative left, top, right, bottom text insets, in that order.
 */
insets: [number, number, number, number],
/**
 * Horizontal text alignment.
 */
alignment: Alignment, };

/**
 * Selected regions supplied by the host's text-selection system.
 */
export type Highlight = {
/**
 * Optional precise live style, taking precedence over compact color/width.
 * Content replacement replaces this style too; retained source never overrides it.
 */
style: ResolvedStyle | null,
/**
 * Nonempty collection of nondegenerate selection quadrilaterals.
 */
quads: Array<Quad>,
/**
 * Fill color used by the host renderer; alpha is the annotation opacity.
 */
color: Color, };

/**
 * Owned HighlightAnnotation data retained from the source PDF.
 */
export type HighlightAnnotation = {
/**
 * The quadrilaterals in perimeter order.
 */
quad_points: Array<Quad>,
/**
 * The annotation color.
 */
color: Color | null,
/**
 * The constant opacity.
 */
constant_opacity: number | null, };

/**
 * Completed freehand strokes; collecting pointer samples belongs to the GUI.
 */
export type Ink = {
/**
 * Optional precise live style, taking precedence over compact color/width.
 * Content replacement replaces this style too; retained source never overrides it.
 */
style: ResolvedStyle | null,
/**
 * Nonempty open strokes, each containing at least two points.
 */
strokes: Array<Polyline>,
/**
 * Finite, strictly positive stroke width in page user-space units.
 */
width: number,
/**
 * Stroke color; alpha is the annotation opacity.
 */
color: Color, };

/**
 * Owned InkAnnotation data retained from the source PDF.
 */
export type InkAnnotation = {
/**
 * The required ink list.
 */
ink_list: InkList,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The interior color.
 */
interior_color: Color | null, };

/**
 * Owned InkList data retained from the source PDF.
 */
export type InkList = {
/**
 * The parsed stroke lists.
 */
strokes: Array<Polyline>, };

/**
 * Owned LineAnnotation data retained from the source PDF.
 */
export type LineAnnotation = {
/**
 * The required line endpoints.
 */
line: [number, number, number, number],
/**
 * The line ending styles.
 */
line_endings: [LineEndingStyle, LineEndingStyle] | null,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The interior color.
 */
interior_color: Color | null,
/**
 * The leader line length.
 */
leader_line_length: number | null,
/**
 * The leader line extension length.
 */
leader_line_extension: number | null,
/**
 * Whether the caption is positioned at the line's end.
 */
caption: boolean | null,
/**
 * The intent.
 */
intent: Array<number> | null, };

/**
 * Owned LineEndingStyle data retained from the source PDF.
 */
export type LineEndingStyle = "Butt" | "Circle" | "Diamond" | "OpenArrow" | "ClosedArrow" | "None" | "Square" | "Slash" | { "Unknown": Array<number> };

/**
 * Link bounds and host-owned navigation metadata; Core executes no actions.
 */
export type Link = {
/**
 * Fallback interaction bounds.
 */
bounds: Rect,
/**
 * Optional quadrilateral interaction regions in perimeter order.
 */
quads: Array<Quad> | null,
/**
 * Pointer highlight feedback metadata.
 */
highlight_mode: LinkHighlightMode | null,
/**
 * Destination used when no action is present.
 */
destination: AnnotationDestination | null,
/**
 * Action metadata taking precedence over the destination.
 */
action: AnnotationAction | null,
/**
 * Current border style.
 */
style: ResolvedStyle, };

/**
 * Owned LinkAnnotation data retained from the source PDF.
 */
export type LinkAnnotation = {
/**
 * The link highlight mode.
 */
highlight_mode: LinkHighlightMode | null,
/**
 * The annotation destination.
 */
destination: AnnotationDestination | null,
/**
 * The annotation action.
 */
action: AnnotationAction | null,
/**
 * The quadrilaterals in perimeter order.
 */
quad_points: Array<Quad> | null,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The border effect.
 */
border_effect: BorderEffect | null, };

/**
 * Owned LinkHighlightMode data retained from the source PDF.
 */
export type LinkHighlightMode = "Invert" | "Outline" | "Push" | "None" | "Toggle" | { "Unknown": Array<number> };

/**
 * A visible choice list with fixed options and selection cardinality.
 */
export type ListBoxField = {
/**
 * Options in presentation order, each with a unique identity; may be empty.
 */
options: Array<ChoiceOption>,
/**
 * Current selection; commands must preserve the single/multiple variant.
 */
selection: ListSelection, };

/**
 * Listbox cardinality encoded together with its current selection.
 */
export type ListSelection = { "mode": "single", "selected": OptionId | null } | { "mode": "multiple", "selected": Array<OptionId> };

/**
 * Underline, squiggly, or strikeout regions, in Core perimeter order.
 */
export type Markup = {
/**
 * Nonempty convex regions, retaining individual quad boundaries.
 */
quads: Array<Quad>,
/**
 * Current stroke/fill style.
 */
style: ResolvedStyle, };

/**
 * Native PDF annotation subtype data.
 */
export type NativeAnnotation = { "Text": TextAnnotation } | { "Link": LinkAnnotation } | { "FreeText": FreeTextAnnotation } | { "Line": LineAnnotation } | { "Square": SquareAnnotation } | { "Circle": CircleAnnotation } | { "Polygon": PolygonAnnotation } | { "PolyLine": PolyLineAnnotation } | { "Highlight": HighlightAnnotation } | { "Underline": UnderlineAnnotation } | { "Squiggly": SquigglyAnnotation } | { "StrikeOut": StrikeOutAnnotation } | { "Stamp": StampAnnotation } | { "Caret": CaretAnnotation } | { "Ink": InkAnnotation } | { "Popup": PopupAnnotation } | { "Widget": WidgetAnnotation } | { "Unknown": {
/**
 * Unrecognized PDF subtype bytes.
 */
subtype: Array<number>, } };

/**
 * Creation input without an identity, which only Core allocates.
 */
export type NewAnnotation = {
/**
 * Live capabilities and retained source information; defaults suit new overlays.
 */
metadata: AnnotationMetadata,
/**
 * Page receiving the annotation.
 */
page: PageIndex,
/**
 * Geometry, content, and styling to validate before insertion.
 */
content: AnnotationKind, };

/**
 * Field creation data without the identity that Core will allocate.
 */
export type NewField = {
/**
 * Historical source properties; never a second live field value.
 */
metadata: FieldMetadata,
/**
 * Host-facing field name; names need not be unique and are not identities.
 */
name: string,
/**
 * Accessible label for native controls.
 */
label: string,
/**
 * Reject value edits while allowing separate structural authoring operations.
 */
read_only: boolean,
/**
 * Include an issue in completeness checks when the value is unfilled.
 */
required: boolean,
/**
 * Fixed configuration and initial value to validate at creation.
 */
content: FieldKind, };

/**
 * Completed edits; transient dragging and drawing previews remain host-owned.
 */
export type Operation = { "operation": "set_checkbox_group_selection",
/**
 * Existing writable checkbox group.
 */
field: FieldId,
/**
 * Existing option identity, or an unchecked draft.
 */
selected: OptionId | null, } | { "operation": "set_free_text_text",
/**
 * Existing plain FreeText annotation with editable contents.
 */
id: AnnotationId,
/**
 * New Unicode text; empty drafts are accepted.
 */
text: string, } | { "operation": "create",
/**
 * Draft data for the new annotation.
 */
annotation: NewAnnotation, } | { "operation": "translate",
/**
 * Existing annotation to move.
 */
id: AnnotationId,
/**
 * Finite displacement in unrotated PDF page user space.
 */
delta: Point, } | { "operation": "replace_content",
/**
 * Existing annotation to edit.
 */
id: AnnotationId,
/**
 * Replacement payload, which must have the same variant as before.
 */
content: AnnotationKind, } | { "operation": "delete",
/**
 * Existing annotation to remove.
 */
id: AnnotationId, } | { "operation": "create_field",
/**
 * Fixed configuration and initial value; incomplete required values are valid.
 */
field: NewField, } | { "operation": "delete_field",
/**
 * Existing, unreferenced field to remove.
 */
field: FieldId, } | { "operation": "set_text",
/**
 * Existing writable text field; combos use `SetComboValue`.
 */
field: FieldId,
/**
 * New Unicode text, including an empty draft.
 */
value: string, } | { "operation": "set_checkbox",
/**
 * Existing writable checkbox field.
 */
field: FieldId,
/**
 * New checked state; false is allowed even when required.
 */
checked: boolean, } | { "operation": "set_radio_selection",
/**
 * Existing writable radio field.
 */
field: FieldId,
/**
 * Existing option, or `None`; clearing an already empty field is allowed.
 */
selected: OptionId | null, } | { "operation": "set_list_selection",
/**
 * Existing writable listbox field.
 */
field: FieldId,
/**
 * Existing option identities; reject duplicates and non-option-list ordering.
 */
selection: ListSelection, } | { "operation": "set_combo_value",
/**
 * Existing writable combo field.
 */
field: FieldId,
/**
 * New value; reject unknown options and custom text in closed combos.
 */
value: ComboValue, };

/**
 * Field-local option identity, independent of its display order or export value.
 */
export type OptionId = number;

/**
 * Zero-based index into the host document's pages.
 */
export type PageIndex = number;

/**
 * Straight line, open polyline, or closed polygon geometry.
 */
export type PathAnnotation = {
/**
 * Annotation rectangle; translations move it together with all vertices.
 */
bounds: Rect,
/**
 * Ordered vertices; `closed` is true only for polygons and never duplicates a vertex.
 */
vertices: Polyline,
/**
 * Optional endpoint decorations, preserving unknown names.
 */
endings: [LineEndingStyle, LineEndingStyle] | null,
/**
 * Current stroke/fill style.
 */
style: ResolvedStyle, };

/**
 * A 2D point.
 */
export type Point = {
/**
 * Horizontal coordinate.
 */
x: number,
/**
 * Vertical coordinate.
 */
y: number, };

/**
 * Owned PolyLineAnnotation data retained from the source PDF.
 */
export type PolyLineAnnotation = {
/**
 * The required polyline vertices.
 */
vertices: Polyline,
/**
 * The line ending styles.
 */
line_endings: [LineEndingStyle, LineEndingStyle] | null,
/**
 * The interior color.
 */
interior_color: Color | null,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The intent.
 */
intent: Array<number> | null, };

/**
 * Owned PolygonAnnotation data retained from the source PDF.
 */
export type PolygonAnnotation = {
/**
 * The required polygon vertices.
 */
vertices: Polyline,
/**
 * The line ending styles.
 */
line_endings: [LineEndingStyle, LineEndingStyle] | null,
/**
 * The interior color.
 */
interior_color: Color | null,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The intent.
 */
intent: Array<number> | null, };

/**
 * One sequence of straight segments, with closure stored separately from vertices.
 *
 * The vertex coordinate type defaults to `f32`.
 */
export type Polyline = {
/**
 * Vertices in order, without duplication of the closing point.
 */
points: Array<Point>,
/**
 * Whether the last vertex connects to the first.
 */
closed: boolean, };

/**
 * Popup attached to an optional Core annotation on the same page.
 */
export type Popup = {
/**
 * Popup placement.
 */
bounds: Rect,
/**
 * Live parent identity, distinct from retained PDF object references.
 */
parent: AnnotationId | null,
/**
 * Initial visibility requested from the host.
 */
open: boolean,
/**
 * Popup text.
 */
text: string, };

/**
 * Owned PopupAnnotation data retained from the source PDF.
 */
export type PopupAnnotation = {
/**
 * The required parent annotation reference.
 */
parent: string | null,
/**
 * Whether the popup is open.
 */
open: boolean | null, };

/**
 * Quadrilateral with four corners in perimeter order.
 */
export type Quad = {
/**
 * Clockwise or counterclockwise perimeter; crossing edges are invalid.
 */
corners: [Point, Point, Point, Point], };

/**
 * Exclusive option selection with optional repeated views of each option.
 */
export type RadioField = {
/**
 * Nonempty options with distinct identities; export values may repeat.
 */
options: Array<ChoiceOption>,
/**
 * Selected option, or an incomplete/unselected draft.
 */
selected: OptionId | null,
/**
 * Whether a value command may clear an existing selection.
 * Initial and loaded unselected drafts remain valid when this is false.
 */
allow_clear: boolean, };

/**
 * An axis-aligned rectangle whose edge coordinate type defaults to `f32`.
 */
export type Rect = {
/**
 * The left edge of the rectangle.
 */
left: number,
/**
 * The top edge of the rectangle.
 */
top: number,
/**
 * The right edge of the rectangle.
 */
right: number,
/**
 * The bottom edge of the rectangle.
 */
bottom: number, };

/**
 * Native style in page units, retaining floating-point color precision.
 */
export type ResolvedStyle = {
/**
 * Opaque text or stroke sRGB color with channels in the range zero through one.
 */
color: Color,
/**
 * Optional opaque interior fill.
 */
background: Color | null,
/**
 * Optional opaque border color.
 */
border_color: Color | null,
/**
 * Nonnegative border width in page units.
 */
border_width: number,
/**
 * Nonnegative dash lengths; empty means solid.
 */
dash: Array<number>,
/**
 * Opacity in the range zero through one.
 */
opacity: number,
/**
 * Positive font size in page units.
 */
font_size: number,
/**
 * Host-facing font family or generic fallback.
 */
font_family: string,
/**
 * Horizontal text alignment.
 */
alignment: Alignment, };

/**
 * Monotonically increasing document edit revision; overflow must be rejected.
 */
export type Revision = string;

/**
 * One primitive in annotation-local top-left units.
 */
export type Shape = { "shape": "polyline",
/**
 * Vertices in drawing order and whether the outline closes back to the first.
 */
path: Polyline,
/**
 * Paint for the outline and interior.
 */
paint: ShapePaint, } | { "shape": "ellipse",
/**
 * Enclosing rectangle.
 */
bounds: Rect,
/**
 * Paint for the outline and interior.
 */
paint: ShapePaint, } | { "shape": "rect",
/**
 * Rectangle edges.
 */
bounds: Rect,
/**
 * Paint for the outline and interior.
 */
paint: ShapePaint, };

/**
 * Fill and stroke of one shape.
 */
export type ShapePaint = {
/**
 * Outline color whose alpha is the outline opacity; `None` draws no outline.
 */
stroke: Color | null,
/**
 * Interior color whose alpha is the interior opacity; `None` leaves the interior unpainted.
 */
fill: Color | null,
/**
 * Outline width in local units.
 */
width: number,
/**
 * Dash lengths; empty means solid.
 */
dash: Array<number>,
/**
 * Round caps and joins instead of the host default.
 */
round: boolean, };

/**
 * Native PDF annotation data retained from a page object.
 */
export type SourceAnnotation = {
/**
 * Original page-local runtime identity; never used as a Core identity.
 */
id: string,
/**
 * Original indirect object number, used to resolve annotation relationships.
 */
object_number: string | null,
/**
 * Opacity applied by native presentation.
 */
opacity: number,
/**
 * The annotation subtype name.
 */
subtype: Array<number>,
/**
 * The optional annotation rectangle from `/Rect`, in PDF page user space
 * where `bottom` is the lower `y` edge. Edges keep their source values and
 * order, so inverted rectangles are preserved rather than normalized.
 */
rect: Rect | null,
/**
 * The optional annotation contents.
 */
contents: Array<number> | null,
/**
 * The optional annotation name from `/NM`.
 */
name: Array<number> | null,
/**
 * The optional annotation flags from `/F`.
 */
flags: number | null,
/**
 * The optional appearance dictionary from `/AP`.
 */
appearance: AppearanceDictionary | null,
/**
 * The optional appearance state from `/AS`.
 */
appearance_state: Array<number> | null,
/**
 * The optional border array from `/Border`.
 */
border: AnnotationBorder | null,
/**
 * The optional annotation color from `/C`, converted from the source
 * device color space to sRGB. An empty `/C` array is retained as a fully
 * transparent color (alpha `0.0`), distinct from an absent entry.
 */
color: Color | null,
/**
 * The optional structure parent index from `/StructParent`.
 */
struct_parent: string | null,
/**
 * The parsed subtype-specific payload.
 */
kind: NativeAnnotation, };

/**
 * Owned SquareAnnotation data retained from the source PDF.
 */
export type SquareAnnotation = {
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The interior color.
 */
interior_color: Color | null,
/**
 * The border effect.
 */
border_effect: BorderEffect | null,
/**
 * The difference rectangle.
 */
difference_rect: [number, number, number, number] | null, };

/**
 * Owned SquigglyAnnotation data retained from the source PDF.
 */
export type SquigglyAnnotation = {
/**
 * The quadrilaterals in perimeter order.
 */
quad_points: Array<Quad>,
/**
 * The annotation color.
 */
color: Color | null,
/**
 * The constant opacity.
 */
constant_opacity: number | null, };

/**
 * Stamp identity. Custom names remain data without claiming artwork support.
 */
export type Stamp = {
/**
 * Page-space stamp rectangle.
 */
bounds: Rect,
/**
 * Original stamp name bytes.
 */
name: Array<number>,
/**
 * Current style.
 */
style: ResolvedStyle, };

/**
 * Owned StampAnnotation data retained from the source PDF.
 */
export type StampAnnotation = {
/**
 * The stamp name.
 */
name: Array<number> | null, };

/**
 * Owned StrikeOutAnnotation data retained from the source PDF.
 */
export type StrikeOutAnnotation = {
/**
 * The quadrilaterals in perimeter order.
 */
quad_points: Array<Quad>,
/**
 * The annotation color.
 */
color: Color | null,
/**
 * The constant opacity.
 */
constant_opacity: number | null, };

/**
 * Owned TextAnnotation data retained from the source PDF.
 */
export type TextAnnotation = {
/**
 * Whether the note popup starts open.
 */
open: boolean | null,
/**
 * The note icon name.
 */
name: Array<number> | null,
/**
 * The annotation state.
 */
state: Array<number> | null,
/**
 * The annotation state model.
 */
state_model: Array<number> | null,
/**
 * The intent name.
 */
intent: Array<number> | null, };

/**
 * Shared Unicode text and its fixed input constraints.
 */
export type TextField = {
/**
 * Presentation and newline behavior.
 */
mode: TextMode,
/**
 * Optional maximum number of Unicode scalar values, not bytes or graphemes.
 */
max_length: number | null,
/**
 * Current text; empty text is a valid draft even for a required field.
 */
value: string, };

/**
 * Native text control behavior; password masking does not encrypt stored text.
 */
export type TextMode = "single_line" | "multiline" | "password";

/**
 * Text attached to an anchor; the host chooses the note widget and appearance.
 */
export type TextNote = {
/**
 * Live note icon, open/state/intent, and extension metadata, when supplied.
 */
properties: TextAnnotation | null,
/**
 * Optional precise live style, taking precedence over compact color/width.
 * Content replacement replaces this style too; retained source never overrides it.
 */
style: ResolvedStyle | null,
/**
 * Position of the note anchor on its page.
 */
anchor: Point,
/**
 * Unicode note content; empty notes are allowed.
 */
text: string,
/**
 * Suggested color for the note marker; alpha is the annotation opacity.
 */
color: Color, };

/**
 * Owned UnderlineAnnotation data retained from the source PDF.
 */
export type UnderlineAnnotation = {
/**
 * The quadrilaterals in perimeter order.
 */
quad_points: Array<Quad>,
/**
 * The annotation color.
 */
color: Color | null,
/**
 * The constant opacity.
 */
constant_opacity: number | null, };

/**
 * Unknown subtype retained explicitly rather than approximated by another kind.
 */
export type UnknownAnnotation = {
/**
 * Original subtype name bytes.
 */
subtype: Array<number>,
/**
 * Optional usable page-space bounds.
 */
bounds: Rect | null, };

/**
 * A field whose value can be retained but has no supported Core value editor.
 */
export type UnsupportedField = {
/**
 * Source field type, including signature, push-button, or unknown types.
 */
field_type: Array<number>,
/**
 * Current retained value, distinct from an absent value.
 */
value: WidgetFieldValue | null, };

/**
 * One projected entry plus its DOM placement.
 */
export type WebAnnotationEntry = {
/**
 * CSS derived from `entry.style`, `entry.transform`, and the viewport.
 */
css: WebCss,
/**
 * Core identity the host echoes back in command targets.
 */
id: AnnotationId,
/**
 * Zero-based page containing the annotation.
 */
page: number,
/**
 * Live Core payload.
 */
content: AnnotationKind,
/**
 * Live presentation style resolved from Core state and retained source data.
 */
style: ResolvedStyle,
/**
 * Host-owned action notification; links fall back to their destination.
 */
action: AnnotationAction | null,
/**
 * Live Unicode contents.
 */
text: string,
/**
 * Displayed subtype name.
 */
subtype: string,
/**
 * Why the host should show a placeholder instead of `annotation.content`.
 */
unsupported: string | null,
/**
 * Device-space interaction rectangles.
 */
bounds: Array<[number, number, number, number]>,
/**
 * Page-space bottom-left corner of the `size` box; local coordinates are
 * `[x - origin[0], origin[1] + size[1] - y]`.
 */
origin: [number, number],
/**
 * Local page-unit width and height.
 */
size: [number, number],
/**
 * Local top-left to device affine matrix.
 */
transform: [number, number, number, number, number, number],
/**
 * Preserve physical size under zoom.
 */
no_zoom: boolean,
/**
 * Preserve orientation under rotation.
 */
no_rotate: boolean,
/**
 * Permit host dragging.
 */
draggable: boolean,
/**
 * Permit editing the content: the FreeText editor, or a widget's field value.
 */
editable: boolean,
/**
 * Show this entry.
 */
visible: boolean,
/**
 * Permit pointer interaction.
 */
interactive: boolean,
/**
 * Document revision that last changed this annotation or its field.
 */
modified_revision: Revision,
/**
 * Decoded stamp name or note icon name; empty for other kinds.
 */
label: string,
/**
 * Validated `http`, `https`, or `mailto` link target.
 */
href: string | null,
/**
 * Whether a popup on this page names this annotation as its parent.
 */
has_popup: boolean,
/**
 * Native control for widgets bound to a supported field.
 */
control: WidgetControl | null,
/**
 * Local-unit outlines for markup, ink, and geometric annotations.
 */
shapes: Array<Shape>, };

/**
 * Ready-to-assign CSS for one annotation container.
 */
export type WebCss = {
/**
 * `matrix(a,b,c,d,e,f)` from annotation-local top-left units to container CSS pixels,
 * honoring the annotation's no-zoom and no-rotate flags.
 */
transform: string,
/**
 * Text or stroke color.
 */
color: string,
/**
 * Interior color, or `transparent`.
 */
background: string,
/**
 * Border shorthand for kinds without vector shapes; empty for none.
 */
border: string, };

/**
 * Annotation geometry and reference to shared field data, without a local value.
 */
export type Widget = {
/**
 * Optional precise current control style, independent of historical PDF metadata.
 */
style: ResolvedStyle | null,
/**
 * Placement on the containing annotation's page.
 * Bounds, including their maximum corner, must remain finite after edits.
 */
bounds: Rect,
/**
 * Immutable binding; delete and create an annotation to change its field/option.
 */
binding: WidgetBinding, };

/**
 * Owned WidgetAnnotation data retained from the source PDF.
 */
export type WidgetAnnotation = {
/**
 * Indirect object number of the terminal field that owns this widget.
 *
 * Widgets belonging to the same logical field share this identifier even
 * when other field properties are inherited from higher ancestors.
 */
field_id: string | null,
/**
 * The form field type.
 */
field_type: Array<number> | null,
/**
 * The field name.
 */
field_name: Array<number> | null,
/**
 * The alternate field name.
 */
alternate_name: Array<number> | null,
/**
 * The mapping name.
 */
mapping_name: Array<number> | null,
/**
 * The field flags.
 */
field_flags: number | null,
/**
 * The value.
 */
value: WidgetFieldValue | null,
/**
 * The default value.
 */
default_value: WidgetFieldValue | null,
/**
 * The default appearance string.
 */
default_appearance: Array<number> | null,
/**
 * The quadding mode.
 */
quadding: number | null,
/**
 * Maximum number of text characters.
 */
max_length: string | null,
/**
 * Options available to a choice field.
 */
options: Array<WidgetChoiceOption> | null,
/**
 * Explicitly selected choice option indices from `/I`.
 */
selected_indices: Array<string> | null,
/**
 * Index of the first visible listbox option from `/TI`.
 */
top_index: string | null,
/**
 * The appearance characteristics.
 */
appearance_characteristics: AppearanceCharacteristics | null,
/**
 * The border style.
 */
border_style: BorderStyle | null,
/**
 * The action dictionary.
 */
action: AnnotationAction | null, };

/**
 * Binding to shared state; a radio widget additionally names its option.
 */
export type WidgetBinding = { "kind": "checkbox_option",
/**
 * Existing checkbox group.
 */
field: FieldId,
/**
 * Option shared by every view with this export state.
 */
option: OptionId, } | { "kind": "field",
/**
 * Existing document field whose kind determines the native control.
 */
field: FieldId, } | { "kind": "radio_option",
/**
 * Existing radio field.
 */
field: FieldId,
/**
 * Existing option in that field.
 */
option: OptionId, };

/**
 * Owned WidgetChoiceOption data retained from the source PDF.
 */
export type WidgetChoiceOption = {
/**
 * Value written to the field when this option is selected.
 */
export_value: Array<number>,
/**
 * Value presented to the user for this option.
 */
display_value: Array<number>, };

/**
 * Native control derived from a widget's resolved Core field; hosts never read PDF flags.
 */
export type WidgetControl = {
/**
 * Element family to create.
 */
tag: ControlTag,
/**
 * Input type for `Input` tags: `text`, `password`, `checkbox`, or `radio`.
 */
input_type: string | null,
/**
 * Field semantics for building commands.
 */
kind: ControlKind,
/**
 * Shared field this widget edits.
 */
field: FieldId,
/**
 * Option this widget toggles within a checkbox or radio group.
 */
option: OptionId | null,
/**
 * Accessible label.
 */
label: string,
/**
 * Whether the field requires a value.
 */
required: boolean,
/**
 * Current text value for text and editable combo controls.
 */
value: string,
/**
 * Maximum text length in Unicode scalar values.
 */
max_length: number | null,
/**
 * Whether a checkbox or radio control is on.
 */
checked: boolean,
/**
 * Push button caption.
 */
caption: string,
/**
 * Choices for list and combo controls.
 */
options: Array<ChoiceOption> | null,
/**
 * Whether several list options may be selected.
 */
multiple: boolean,
/**
 * Present choices as a visible list instead of a drop-down.
 */
list_box: boolean,
/**
 * Indices into `options` that are selected.
 */
selected: Array<number>,
/**
 * Index of the first visible list option.
 */
top_index: number,
/**
 * Counterclockwise content rotation in degrees from the source appearance.
 */
rotation: number, };

/**
 * Owned WidgetFieldValue data retained from the source PDF.
 */
export type WidgetFieldValue = { "Bytes": Array<number> } | "Dictionary" | { "Array": Array<WidgetFieldValue> } | "Null";
