[package]
name = "pdf-content-stream-operators"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
bytes = "1.10.1"
pdf-parser = { path = "../pdf-parser" }
pdf-tokenizer = { path = "../pdf-tokenizer" }
pdf-object = { path = "../pdf-object" }
pdf-image = { path = "../pdf-image" }
pdf-graphics = { path = "../pdf-graphics" }
thiserror = "2.0.12"
num-traits = "0.2.19"
