[package]
name = "pdf-canvas"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
pdf-content-stream-operators = { path = "../pdf-content-stream-operators" }
pdf-content-stream = { path = "../pdf-content-stream" }
pdf-document = { path = "../pdf-document" }
pdf-resources = { path = "../pdf-resources" }
pdf-image = { path = "../pdf-image" }
pdf-font = { path = "../pdf-font" }
pdf-object = { path = "../pdf-object" }
pdf-graphics = { path = "../pdf-graphics" }
pdf-shading = { path = "../pdf-shading" }
pdf-color-space = { path = "../pdf-color-space" }
thiserror = "2.0.12"
num-traits = "0.2.19"
read-fonts = "0.39.2"
skrifa =  "0.42.1"