[package]
name = "pdf-annotation-types"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bitflags = "2.9.1"
pdf-object-reader = { path = "../pdf-object-reader" }
pdf-graphics = { path = "../pdf-graphics" }
pdf-content-stream = { path = "../pdf-content-stream" }
pdf-resources = { path = "../pdf-resources" }
thiserror = "2.0.12"
num-traits = "0.2.19"
