[package]
name = "pdf-object"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
num-traits = "0.2.19"
thiserror = "2.0.12"