[package]
name = "pdf-object"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[features]
default = []

[dependencies]
num-traits = "0.2.19"
thiserror = "2.0.12"
flate2 = "1.1.1"
jpeg2k = "0.10.1"
image = { version = "0.25.9", default-features = false, features = ["jpeg"] }
