[package]
name = "pdf-font"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
pdf-object = { path = "../pdf-object" }
pdf-parser = { path = "../pdf-parser" }
pdf-cmap = { path = "../pdf-cmap" }
pdf-content-stream-operators = { path = "../pdf-content-stream-operators" }
pdf-content-stream = { path = "../pdf-content-stream" }
pdf-graphics = { path = "../pdf-graphics" }
bitflags = "2.9.1"
thiserror = "2.0.12"
num-traits = "0.2.19"
num-derive = "0.4"
read-fonts = "0.39.2"
write-fonts = "0.44.1"
