[package]
name = "pdf-font"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-object = { path = "../pdf-object" }
pdf-content-stream = { path = "../pdf-content-stream" }
bitflags = "2.9.1"
thiserror = "2.0.12"