[package]
name = "pdf-image"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
pdf-decode = { path = "../pdf-decode" }
pdf-object = { path = "../pdf-object" }
pdf-graphics = { path = "../pdf-graphics" }
pdf-color-space = { path = "../pdf-color-space" }
pdf-filter = { path = "../pdf-filter" }
thiserror = "2.0.12"
num-traits = "0.2"
