[package]
name = "pdf-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-annotations = { path = "../pdf-annotations" }
pdf-content-stream = { path = "../pdf-content-stream" }
pdf-document = { path = "../pdf-document" }
pdf-canvas = { path = "../pdf-canvas" }
pdf-graphics = { path = "../pdf-graphics" }
thiserror = "2.0.12"

[dev-dependencies]
pdf-font = { path = "../pdf-font" }
