[package]
name = "pdf-renderer"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-operator = { path = "../pdf-operator" }
pdf-page = { path = "../pdf-page" }
pdf-document = { path = "../pdf-document" }
pdf-graphics = { path = "../pdf-graphics" }