[package]
name = "pdf-parser"
version = "0.1.0"
edition = "2024"

# Inherit all lint configurations from the workspace root
[lints]
workspace = true

[dependencies]
pdf-tokenizer = { path = "../pdf-tokenizer" }
pdf-object = { path = "../pdf-object" }
flate2 = "1.1.1"
thiserror = "2.0.12"