[package]
name = "pdf-document"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-content-stream = { path = "../pdf-content-stream" }
pdf-annotation-types = { path = "../pdf-annotation-types" }
pdf-object-collection = { path = "../pdf-object-collection" }
pdf-object = { path = "../pdf-object" }
pdf-parser = { path = "../pdf-parser" }
pdf-resources = { path = "../pdf-resources" }
pdf-graphics = { path = "../pdf-graphics" }
thiserror = "2.0.12"

md-5 = "0.10.6"
sha2 = "0.10.9"
aes = "0.8.4"
cbc = "0.1.2"
rc4 = "0.1.0"
stringprep = "0.1.5"

[lints]
workspace = true

[dev-dependencies]
pdf-color-space = { path = "../pdf-color-space" }
