[package]
name = "pdf-document"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-object = { path = "../pdf-object" }
pdf-parser = { path = "../pdf-parser" }
pdf-page = { path = "../pdf-page" }
pdf-font = { path = "../pdf-font" }
thiserror = "2.0.12"