use std::sync::Arc;

use pdf_image::InlineImage;

use crate::compatibility_operators::{BeginCompatibility, EndCompatibility};
use crate::{
    clipping_path_operators::*,
    color_operators::*,
    graphics_state_operators::*,
    marked_content_operators::*,
    operator_trait::PdfOperator,
    path_operators::*,
    path_paint_operators::*,
    pdf_operator_backend::{BackendError, PdfOperatorBackend},
    shadings_operators::PaintShading,
    text_object_operators::*,
    text_positioning_operators::*,
    text_showing_operators::*,
    text_state_operators::*,
    type3_font_operators::{SetCharWidth, SetCharWidthAndBoundingBox},
    xobject_and_image_operators::*,
};

#[derive(Debug, Clone)]
pub enum PdfOperatorVariant {
    LineTo(LineTo),
    MoveTo(MoveTo),
    CurveTo(CurveTo),
    CurveToV(CurveToV),
    CurveToY(CurveToY),
    ClosePath(ClosePath),
    Rectangle(Rectangle),
    StrokePath(StrokePath),
    CloseStrokePath(CloseStrokePath),
    FillPathNonZero(FillPathNonZero),
    FillPathEvenOdd(FillPathEvenOdd),
    FillAndStrokePathNonZero(FillAndStrokePathNonZero),
    FillAndStrokePathEvenOdd(FillAndStrokePathEvenOdd),
    CloseFillAndStrokePathNonZero(CloseFillAndStrokePathNonZero),
    CloseFillAndStrokePathEvenOdd(CloseFillAndStrokePathEvenOdd),
    EndPath(EndPath),
    ClipNonZero(ClipNonZero),
    ClipEvenOdd(ClipEvenOdd),
    SetGrayFill(SetGrayFill),
    SetGrayStroke(SetGrayStroke),
    SetRGBFill(SetRGBFill),
    SetRGBStroke(SetRGBStroke),
    SetCMYKFill(SetCMYKFill),
    SetCMYKStroke(SetCMYKStroke),
    SetLineWidth(SetLineWidth),
    SetLineCapStyle(SetLineCapStyle),
    SetLineJoinStyle(SetLineJoinStyle),
    SetMiterLimit(SetMiterLimit),
    SetDashPattern(SetDashPattern),
    SetFlatnessTolerance(SetFlatnessTolerance),
    SetGraphicsStateFromDict(SetGraphicsStateFromDict),
    SaveGraphicsState(SaveGraphicsState),
    RestoreGraphicsState(RestoreGraphicsState),
    ConcatMatrix(ConcatMatrix),
    BeginMarkedContent(BeginMarkedContent),
    BeginMarkedContentWithProps(BeginMarkedContentWithProps),
    EndMarkedContent(EndMarkedContent),
    BeginText(BeginText),
    EndText(EndText),
    MoveTextPosition(MoveTextPosition),
    MoveTextPositionAndSetLeading(MoveTextPositionAndSetLeading),
    SetTextMatrix(SetTextMatrix),
    MoveToNextLine(MoveToNextLine),
    ShowText(ShowText),
    MoveNextLineShowText(MoveNextLineShowText),
    SetSpacingMoveShowText(SetSpacingMoveShowText),
    ShowTextArray(ShowTextArray),
    SetCharacterSpacing(SetCharacterSpacing),
    SetWordSpacing(SetWordSpacing),
    SetHorizontalScaling(SetHorizontalScaling),
    SetLeading(SetLeading),
    SetFont(SetFont),
    SetRenderingMode(SetRenderingMode),
    SetTextRise(SetTextRise),
    InvokeXObject(InvokeXObject),
    BeginCompatibility(BeginCompatibility),
    InlineImage(Arc<InlineImage>),
    EndCompatibility(EndCompatibility),
    PaintShading(PaintShading),
    SetCharWidthAndBoundingBox(SetCharWidthAndBoundingBox),
    SetCharWidth(SetCharWidth),
    SetRenderingIntent(SetRenderingIntent),
    SetStrokeColorSpace(SetStrokeColorSpace),
    SetNonStrokingColorSpace(SetNonStrokingColorSpace),
    SetStrokingColor(SetStrokingColor),
    SetNonStrokingColor(SetNonStrokingColor),
}

impl PdfOperatorVariant {
    pub fn call<T: PdfOperatorBackend>(&self, backend: &mut T) -> Result<(), BackendError<T>> {
        match self {
            PdfOperatorVariant::LineTo(op) => op.call(backend),
            PdfOperatorVariant::MoveTo(op) => op.call(backend),
            PdfOperatorVariant::CurveTo(op) => op.call(backend),
            PdfOperatorVariant::CurveToV(op) => op.call(backend),
            PdfOperatorVariant::CurveToY(op) => op.call(backend),
            PdfOperatorVariant::ClosePath(op) => op.call(backend),
            PdfOperatorVariant::Rectangle(op) => op.call(backend),
            PdfOperatorVariant::StrokePath(op) => op.call(backend),
            PdfOperatorVariant::CloseStrokePath(op) => op.call(backend),
            PdfOperatorVariant::FillPathNonZero(op) => op.call(backend),
            PdfOperatorVariant::FillPathEvenOdd(op) => op.call(backend),
            PdfOperatorVariant::FillAndStrokePathNonZero(op) => op.call(backend),
            PdfOperatorVariant::FillAndStrokePathEvenOdd(op) => op.call(backend),
            PdfOperatorVariant::CloseFillAndStrokePathNonZero(op) => op.call(backend),
            PdfOperatorVariant::CloseFillAndStrokePathEvenOdd(op) => op.call(backend),
            PdfOperatorVariant::EndPath(op) => op.call(backend),
            PdfOperatorVariant::ClipNonZero(op) => op.call(backend),
            PdfOperatorVariant::ClipEvenOdd(op) => op.call(backend),
            PdfOperatorVariant::SetGrayFill(op) => op.call(backend),
            PdfOperatorVariant::SetGrayStroke(op) => op.call(backend),
            PdfOperatorVariant::SetRGBFill(op) => op.call(backend),
            PdfOperatorVariant::SetRGBStroke(op) => op.call(backend),
            PdfOperatorVariant::SetCMYKFill(op) => op.call(backend),
            PdfOperatorVariant::SetCMYKStroke(op) => op.call(backend),
            PdfOperatorVariant::SetLineWidth(op) => op.call(backend),
            PdfOperatorVariant::SetLineCapStyle(op) => op.call(backend),
            PdfOperatorVariant::SetLineJoinStyle(op) => op.call(backend),
            PdfOperatorVariant::SetMiterLimit(op) => op.call(backend),
            PdfOperatorVariant::SetDashPattern(op) => op.call(backend),
            PdfOperatorVariant::SetFlatnessTolerance(op) => op.call(backend),
            PdfOperatorVariant::SetGraphicsStateFromDict(op) => op.call(backend),
            PdfOperatorVariant::SaveGraphicsState(op) => op.call(backend),
            PdfOperatorVariant::RestoreGraphicsState(op) => op.call(backend),
            PdfOperatorVariant::ConcatMatrix(op) => op.call(backend),
            PdfOperatorVariant::BeginMarkedContent(op) => op.call(backend),
            PdfOperatorVariant::BeginMarkedContentWithProps(op) => op.call(backend),
            PdfOperatorVariant::EndMarkedContent(op) => op.call(backend),
            PdfOperatorVariant::BeginText(op) => op.call(backend),
            PdfOperatorVariant::EndText(op) => op.call(backend),
            PdfOperatorVariant::MoveTextPosition(op) => op.call(backend),
            PdfOperatorVariant::MoveTextPositionAndSetLeading(op) => op.call(backend),
            PdfOperatorVariant::SetTextMatrix(op) => op.call(backend),
            PdfOperatorVariant::MoveToNextLine(op) => op.call(backend),
            PdfOperatorVariant::ShowText(op) => op.call(backend),
            PdfOperatorVariant::MoveNextLineShowText(op) => op.call(backend),
            PdfOperatorVariant::SetSpacingMoveShowText(op) => op.call(backend),
            PdfOperatorVariant::ShowTextArray(op) => op.call(backend),
            PdfOperatorVariant::SetCharacterSpacing(op) => op.call(backend),
            PdfOperatorVariant::SetWordSpacing(op) => op.call(backend),
            PdfOperatorVariant::SetHorizontalScaling(op) => op.call(backend),
            PdfOperatorVariant::SetLeading(op) => op.call(backend),
            PdfOperatorVariant::SetFont(op) => op.call(backend),
            PdfOperatorVariant::SetRenderingMode(op) => op.call(backend),
            PdfOperatorVariant::SetTextRise(op) => op.call(backend),
            PdfOperatorVariant::InvokeXObject(op) => op.call(backend),
            PdfOperatorVariant::BeginCompatibility(op) => op.call(backend),
            PdfOperatorVariant::InlineImage(op) => op.call(backend),
            PdfOperatorVariant::EndCompatibility(op) => op.call(backend),
            PdfOperatorVariant::PaintShading(op) => op.call(backend),
            PdfOperatorVariant::SetCharWidthAndBoundingBox(op) => op.call(backend),
            PdfOperatorVariant::SetCharWidth(op) => op.call(backend),
            PdfOperatorVariant::SetRenderingIntent(op) => op.call(backend),
            PdfOperatorVariant::SetStrokeColorSpace(op) => op.call(backend),
            PdfOperatorVariant::SetNonStrokingColorSpace(op) => op.call(backend),
            PdfOperatorVariant::SetStrokingColor(op) => op.call(backend),
            PdfOperatorVariant::SetNonStrokingColor(op) => op.call(backend),
        }
    }
}
