[package]
name = "pdf-graphics-femtovg"
version = "0.1.0"
edition = "2024"


[dependencies]
femtovg = { version = "0.14.0", features = ["wgpu"] }
pdf-document = { path = "../pdf-document" }
pdf-canvas = { path = "../pdf-canvas" }
pdf-graphics = { path = "../pdf-graphics" }