[package]
name = "pdf-annotations"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
pdf-annotation-types = { path = "../pdf-annotation-types" }
pdf-canvas = { path = "../pdf-canvas" }
pdf-graphics = { path = "../pdf-graphics" }
thiserror = "2.0.12"

[dev-dependencies]
pdf-document = { path = "../pdf-document" }
pdf-font = { path = "../pdf-font" }
pdf-text-engine = { path = "../pdf-text-engine" }
