[package]
name = "pdf-annotations"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
pdf-annotation-types = { path = "../pdf-annotation-types" }
pdf-canvas = { path = "../pdf-canvas" }
pdf-document = { path = "../pdf-document" }
pdf-color-space = { path = "../pdf-color-space" }
pdf-content-stream-operators = { path = "../pdf-content-stream-operators" }
pdf-graphics = { path = "../pdf-graphics" }
pdf-object = { path = "../pdf-object" }
pdf-parser = { path = "../pdf-parser" }
pdf-resources = { path = "../pdf-resources" }
thiserror = "2.0.12"

[dev-dependencies]
